// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-politicians.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";

// src/data/politiciansData.ts
var politiciansData = [
  {
    id: "1",
    name: "Luiz In\xE1cio Lula da Silva",
    party: "PT",
    position: "Presidente da Rep\xFAblica",
    state: "S\xE3o Paulo",
    district: void 0,
    birthPlace: "Caet\xE9s, PE",
    mandates: [
      { position: "Deputado Federal (SP)", start: "1987", end: "1991" },
      { position: "Presidente da Rep\xFAblica", start: "2003", end: "2006" },
      { position: "Presidente da Rep\xFAblica", start: "2007", end: "2010" },
      { position: "Presidente da Rep\xFAblica", start: "2023", end: "2027", current: true }
    ],
    termStart: "2023-01-01",
    termEnd: "2027-01-01",
    imageUrl: "",
    biography: "Luiz In\xE1cio Lula da Silva, nascido em 27 de outubro de 1945 em Caet\xE9s, Pernambuco, \xE9 o 39\xBA presidente do Brasil, exercendo seu terceiro mandato desde 1\xBA de janeiro de 2023. Metal\xFArgico e sindicalista, foi presidente do Sindicato dos Metal\xFArgicos do ABC e cofundador do Partido dos Trabalhadores (PT) em 1980. Governou o Brasil de 2003 a 2010, per\xEDodo marcado por programas sociais como o Bolsa Fam\xEDlia e o Fome Zero, que retiraram milh\xF5es de brasileiros da pobreza. Em seu atual mandato, retomou pol\xEDticas de combate \xE0 fome, prote\xE7\xE3o ambiental na Amaz\xF4nia e reinser\xE7\xE3o do Brasil na diplomacia internacional.",
    website: "https://www.gov.br/planalto",
    email: "contato@planalto.gov.br",
    phone: "@lulaoficial",
    committeeMemberships: ["BRICS", "G20", "MERCOSUL", "CELAC"],
    voteRecords: [
      {
        id: "v1",
        title: "Novo Arcabou\xE7o Fiscal",
        description: "San\xE7\xE3o da Lei Complementar que substituiu o Teto de Gastos por uma nova regra fiscal.",
        date: "2023-08-30",
        vote: "Yes",
        billNumber: "LC 200/2023",
        category: "Economia",
        sources: [
          { label: "Planalto \u2014 LC 200/2023", url: "https://www.planalto.gov.br/ccivil_03/leis/lcp/lcp200.htm" }
        ]
      },
      {
        id: "v2",
        title: "Reforma Tribut\xE1ria",
        description: "Promulga\xE7\xE3o da Emenda Constitucional que unifica impostos sobre o consumo (CBS, IBS e IS).",
        date: "2023-12-20",
        vote: "Yes",
        billNumber: "EC 132/2023",
        category: "Economia",
        sources: [
          { label: "Planalto \u2014 EC 132/2023", url: "https://www.planalto.gov.br/ccivil_03/constituicao/emendas/emc/emc132.htm" }
        ]
      },
      {
        id: "v3",
        title: "Marco Temporal de Terras Ind\xEDgenas",
        description: "Veto parcial ao projeto que estabelecia marco temporal para demarca\xE7\xE3o de terras ind\xEDgenas.",
        date: "2023-10-20",
        vote: "No",
        billNumber: "Lei 14.701/2023",
        category: "Meio Ambiente",
        sources: [
          { label: "Planalto \u2014 Lei 14.701/2023", url: "https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2023/lei/L14701.htm" }
        ]
      },
      {
        id: "v16",
        title: "Igualdade Salarial entre Mulheres e Homens",
        description: "San\xE7\xE3o da lei que assegura igualdade de remunera\xE7\xE3o para o mesmo trabalho ou fun\xE7\xE3o.",
        date: "2023-07-03",
        vote: "Yes",
        billNumber: "Lei 14.611/2023",
        category: "Trabalho",
        sources: [
          { label: "Planalto \u2014 Lei 14.611/2023", url: "https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2023/lei/l14611.htm" }
        ]
      },
      {
        id: "v17",
        title: "Programa Desenrola Brasil",
        description: "San\xE7\xE3o do programa de renegocia\xE7\xE3o de d\xEDvidas de pessoas f\xEDsicas com institui\xE7\xF5es financeiras.",
        date: "2023-10-04",
        vote: "Yes",
        billNumber: "Lei 14.690/2023",
        category: "Economia",
        sources: [
          { label: "Planalto \u2014 Lei 14.690/2023", url: "https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2023/lei/L14690.htm" }
        ]
      },
      {
        id: "v18",
        title: "Programa P\xE9-de-Meia",
        description: "San\xE7\xE3o da poupan\xE7a para estudantes do ensino m\xE9dio p\xFAblico como incentivo \xE0 perman\xEAncia escolar.",
        date: "2024-01-16",
        vote: "Yes",
        billNumber: "Lei 14.818/2024",
        category: "Educa\xE7\xE3o",
        sources: [
          { label: "Planalto \u2014 Lei 14.818/2024", url: "https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2024/lei/l14818.htm" }
        ]
      },
      {
        id: "v19",
        title: "Taxa\xE7\xE3o de Fundos Exclusivos e Offshores",
        description: "San\xE7\xE3o da lei que tributa rendimentos de fundos exclusivos no Brasil e investimentos no exterior.",
        date: "2023-12-12",
        vote: "Yes",
        billNumber: "Lei 14.754/2023",
        category: "Economia",
        sources: [
          { label: "Planalto \u2014 Lei 14.754/2023", url: "https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2023/lei/l14754.htm" }
        ]
      },
      {
        id: "v20",
        title: "Mobilidade El\xE9trica e Sustent\xE1vel (Mover)",
        description: "San\xE7\xE3o do programa de incentivo \xE0 ind\xFAstria automotiva verde e descarboniza\xE7\xE3o.",
        date: "2024-08-13",
        vote: "Yes",
        billNumber: "Lei 14.902/2024",
        category: "Ind\xFAstria",
        sources: [
          { label: "Planalto \u2014 Lei 14.902/2024", url: "https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2024/lei/L14902.htm" }
        ]
      },
      {
        id: "v21",
        title: "Combust\xEDvel do Futuro",
        description: "San\xE7\xE3o da lei que amplia a mistura de etanol na gasolina e cria mercado de combust\xEDveis sustent\xE1veis.",
        date: "2024-10-08",
        vote: "Yes",
        billNumber: "Lei 14.993/2024",
        category: "Meio Ambiente",
        sources: [
          { label: "Planalto \u2014 Lei 14.993/2024", url: "https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2024/lei/L14993.htm" }
        ]
      },
      {
        id: "v22",
        title: "Derrubada do Veto ao Marco Temporal",
        description: "Congresso Nacional derrubou o veto presidencial ao marco temporal de terras ind\xEDgenas; governo foi derrotado.",
        date: "2023-12-14",
        vote: "No",
        billNumber: "Lei 14.701/2023 (veto)",
        category: "Meio Ambiente",
        sources: [
          { label: "Congresso Nacional \u2014 Sess\xE3o Conjunta 14/12/2023", url: "https://www.congressonacional.leg.br/materias/vetos/-/veto/detalhe/15375" }
        ]
      },
      {
        id: "v23",
        title: "Reonera\xE7\xE3o da Folha de Pagamento",
        description: "Governo tentou reonerar a folha de 17 setores via MP; derrotado, recuou e sancionou desonera\xE7\xE3o at\xE9 2027.",
        date: "2024-09-16",
        vote: "No",
        billNumber: "Lei 14.973/2024",
        category: "Economia",
        sources: [
          { label: "Planalto \u2014 Lei 14.973/2024", url: "https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2024/lei/L14973.htm" }
        ]
      },
      {
        id: "v24",
        title: "MP 1.227/2024 \u2014 Limite a cr\xE9ditos de PIS/Cofins",
        description: "Medida Provis\xF3ria editada pelo governo para limitar compensa\xE7\xE3o de cr\xE9ditos tribut\xE1rios; teve trechos devolvidos pelo Congresso ap\xF3s forte rejei\xE7\xE3o do setor produtivo.",
        date: "2024-06-04",
        vote: "Yes",
        billNumber: "MP 1.227/2024",
        category: "Economia",
        sources: [
          { label: "Senado \u2014 MP 1.227/2024", url: "https://www25.senado.leg.br/web/atividade/materias/-/materia/164093" }
        ]
      }
    ],
    promises: [
      {
        id: "p1",
        title: "Acabar com a Fome no Brasil",
        description: "Retomar e ampliar o programa Brasil Sem Fome para tirar o pa\xEDs do Mapa da Fome da ONU/FAO.",
        datePromised: "2022-10-30",
        deadline: "2026-12-31",
        status: "Fulfilled",
        progress: 100,
        category: "Social",
        sources: [
          { label: "Plano Brasil Sem Fome \u2014 gov.br", url: "https://www.gov.br/mds/pt-br/acoes-e-programas/brasil-sem-fome" },
          { label: "FAO \u2014 SOFI 2024", url: "https://www.fao.org/publications/sofi/2024/en/" }
        ]
      },
      {
        id: "p2",
        title: "Desmatamento Zero na Amaz\xF4nia",
        description: "Combater o desmatamento ilegal e alcan\xE7ar desmatamento zero na Amaz\xF4nia at\xE9 2030.",
        datePromised: "2022-10-30",
        deadline: "2030-12-31",
        status: "In Progress",
        progress: 50,
        category: "Meio Ambiente",
        sources: [
          { label: "INPE \u2014 PRODES", url: "http://terrabrasilis.dpi.inpe.br/app/dashboard/deforestation/biomes/legal_amazon/rates" }
        ]
      },
      {
        id: "p3",
        title: "Reajuste Real do Sal\xE1rio M\xEDnimo",
        description: "Pol\xEDtica de valoriza\xE7\xE3o que garante reajuste do sal\xE1rio m\xEDnimo acima da infla\xE7\xE3o (INPC + PIB).",
        datePromised: "2022-10-30",
        deadline: "2026-12-31",
        status: "Fulfilled",
        progress: 100,
        category: "Economia",
        sources: [
          { label: "Planalto \u2014 Lei 14.663/2023", url: "https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2023/lei/L14663.htm" }
        ]
      },
      {
        id: "p16",
        title: "Retomar o Minha Casa Minha Vida",
        description: "Relan\xE7ar o programa habitacional com meta de 2 milh\xF5es de moradias at\xE9 2026.",
        datePromised: "2022-10-30",
        deadline: "2026-12-31",
        status: "In Progress",
        progress: 45,
        category: "Habita\xE7\xE3o",
        sources: [
          { label: "gov.br \u2014 Minha Casa Minha Vida", url: "https://www.gov.br/cidades/pt-br/acesso-a-informacao/acoes-e-programas/habitacao/minha-casa-minha-vida" }
        ]
      },
      {
        id: "p17",
        title: "Reforma Tribut\xE1ria sobre o Consumo",
        description: "Aprovar reforma tribut\xE1ria simplificando impostos sobre consumo (PIS/Cofins/ICMS/ISS).",
        datePromised: "2022-10-30",
        deadline: "2026-12-31",
        status: "Fulfilled",
        progress: 100,
        category: "Economia",
        sources: [
          { label: "Planalto \u2014 EC 132/2023", url: "https://www.planalto.gov.br/ccivil_03/constituicao/emendas/emc/emc132.htm" }
        ]
      },
      {
        id: "p18",
        title: "Retomada de Obras Paradas (Novo PAC)",
        description: "Lan\xE7ar Novo PAC com R$ 1,7 trilh\xE3o em investimentos em infraestrutura at\xE9 2026.",
        datePromised: "2022-10-30",
        deadline: "2026-12-31",
        status: "In Progress",
        progress: 40,
        category: "Infraestrutura",
        sources: [
          { label: "gov.br \u2014 Novo PAC", url: "https://www.gov.br/casacivil/pt-br/novopac" }
        ]
      },
      {
        id: "p19",
        title: "Reinser\xE7\xE3o do Brasil na Diplomacia",
        description: "Recolocar o Brasil em f\xF3runs internacionais (BRICS, G20, COP, ONU) com protagonismo.",
        datePromised: "2022-10-30",
        deadline: "2026-12-31",
        status: "Fulfilled",
        progress: 100,
        category: "Pol\xEDtica Externa",
        sources: [
          { label: "Itamaraty \u2014 Presid\xEAncia G20 2024", url: "https://www.gov.br/mre/pt-br/g20" }
        ]
      },
      {
        id: "p20",
        title: "Cumprir meta fiscal de d\xE9ficit zero em 2024",
        description: "Compromisso p\xFAblico de zerar o d\xE9ficit prim\xE1rio do Governo Central em 2024, conforme arcabou\xE7o fiscal.",
        datePromised: "2023-04-18",
        deadline: "2024-12-31",
        status: "Broken",
        progress: 10,
        category: "Economia",
        sources: [
          { label: "Tesouro Nacional \u2014 Resultado do Tesouro", url: "https://www.gov.br/tesouronacional/pt-br/estatisticas-fiscais-e-planejamento/resultado-do-tesouro-nacional" },
          { label: "Min. Fazenda \u2014 Mudan\xE7a da meta (LDO)", url: "https://www.gov.br/fazenda/pt-br" }
        ]
      },
      {
        id: "p21",
        title: "Reonerar a folha de pagamento de 17 setores",
        description: "Promessa de reonerar gradualmente setores beneficiados pela desonera\xE7\xE3o da folha para sustentar a Previd\xEAncia.",
        datePromised: "2023-08-30",
        deadline: "2024-12-31",
        status: "Broken",
        progress: 20,
        category: "Economia",
        sources: [
          { label: "Planalto \u2014 Lei 14.973/2024 (manteve desonera\xE7\xE3o at\xE9 2027)", url: "https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2024/lei/L14973.htm" }
        ]
      },
      {
        id: "p22",
        title: "Zerar a fila do SUS para cirurgias eletivas",
        description: "Compromisso de zerar a fila de procedimentos eletivos do SUS por meio do Programa Nacional de Redu\xE7\xE3o de Filas.",
        datePromised: "2023-05-30",
        deadline: "2026-12-31",
        status: "In Progress",
        progress: 25,
        category: "Sa\xFAde",
        sources: [
          { label: "Minist\xE9rio da Sa\xFAde \u2014 Redu\xE7\xE3o de Filas", url: "https://www.gov.br/saude/pt-br/assuntos/noticias/2023/maio/ministerio-da-saude-lanca-programa-de-reducao-de-filas-no-sus" },
          { label: "CONASS", url: "https://www.conass.org.br/" }
        ]
      },
      {
        id: "p23",
        title: "N\xE3o privatizar Petrobras e reverter privatiza\xE7\xE3o da Eletrobras",
        description: "Compromisso de campanha de barrar privatiza\xE7\xF5es de estatais estrat\xE9gicas e rever a venda da Eletrobras.",
        datePromised: "2022-10-30",
        deadline: "2026-12-31",
        status: "Broken",
        progress: 30,
        category: "Energia",
        sources: [
          { label: "Ag\xEAncia C\xE2mara \u2014 Eletrobras", url: "https://www.camara.leg.br/noticias/873912-camara-aprova-mp-da-privatizacao-da-eletrobras" }
        ]
      },
      {
        id: "p24",
        title: "Revogar o Teto de Gastos sem aumentar a d\xEDvida",
        description: "Substituir o Teto de Gastos por novo arcabou\xE7o fiscal mantendo a d\xEDvida p\xFAblica em trajet\xF3ria sustent\xE1vel.",
        datePromised: "2022-12-15",
        deadline: "2026-12-31",
        status: "In Progress",
        progress: 35,
        category: "Economia",
        sources: [
          { label: "Planalto \u2014 LC 200/2023", url: "https://www.planalto.gov.br/ccivil_03/leis/lcp/lcp200.htm" },
          { label: "BCB \u2014 Estat\xEDsticas Fiscais", url: "https://www.bcb.gov.br/estatisticas/estatisticasfiscais" }
        ]
      }
    ],
    proposals: [
      {
        id: "pr1",
        title: "Nova Ind\xFAstria Brasil (NIB)",
        description: "Plano de neoindustrializa\xE7\xE3o com R$ 300 bilh\xF5es at\xE9 2026 em transi\xE7\xE3o energ\xE9tica, sa\xFAde, agro sustent\xE1vel e defesa.",
        dateProposed: "2024-01-22",
        status: "Active",
        category: "Economia",
        supportLevel: 65,
        sources: [
          { label: "gov.br \u2014 Nova Ind\xFAstria Brasil", url: "https://www.gov.br/mdic/pt-br/composicao/se/cndi/plano-de-acao" }
        ]
      },
      {
        id: "pr2",
        title: "Programa P\xE9-de-Meia",
        description: "Poupan\xE7a de at\xE9 R$ 9.200 para estudantes do ensino m\xE9dio p\xFAblico como incentivo \xE0 perman\xEAncia escolar.",
        dateProposed: "2024-01-16",
        status: "Passed",
        category: "Educa\xE7\xE3o",
        supportLevel: 82,
        sources: [
          { label: "Planalto \u2014 Lei 14.818/2024", url: "https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2024/lei/l14818.htm" }
        ]
      },
      {
        id: "pr11",
        title: "Programa Acredita",
        description: "Programa de cr\xE9dito e microcr\xE9dito para fam\xEDlias de baixa renda e MPEs.",
        dateProposed: "2024-04-22",
        status: "Passed",
        category: "Economia",
        supportLevel: 70,
        sources: [
          { label: "Planalto \u2014 Lei 14.995/2024", url: "https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2024/lei/L14995.htm" }
        ]
      },
      {
        id: "pr12",
        title: "Reforma do Imposto de Renda",
        description: "Proposta de isen\xE7\xE3o do IR para quem recebe at\xE9 R$ 5 mil mensais, com compensa\xE7\xE3o via tributa\xE7\xE3o dos super-ricos.",
        dateProposed: "2025-03-18",
        status: "Active",
        category: "Economia",
        supportLevel: 75,
        sources: [
          { label: "C\xE2mara \u2014 PL 1087/2025", url: "https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2495334" }
        ]
      },
      {
        id: "pr13",
        title: "Plano de Transforma\xE7\xE3o Ecol\xF3gica",
        description: "Estrat\xE9gia nacional para transi\xE7\xE3o verde, finan\xE7as sustent\xE1veis e descarboniza\xE7\xE3o da economia.",
        dateProposed: "2023-08-09",
        status: "Active",
        category: "Meio Ambiente",
        supportLevel: 68,
        sources: [
          { label: "Minist\xE9rio da Fazenda \u2014 PTE", url: "https://www.gov.br/fazenda/pt-br/orgaos/spe/transformacao-ecologica" }
        ]
      },
      {
        id: "pr14",
        title: "MP 1.227/2024 \u2014 Compensa\xE7\xE3o de PIS/Cofins",
        description: "Medida Provis\xF3ria que limitava a compensa\xE7\xE3o de cr\xE9ditos tribut\xE1rios para conter o d\xE9ficit; trechos centrais foram devolvidos pelo presidente do Congresso ap\xF3s rea\xE7\xE3o do setor produtivo.",
        dateProposed: "2024-06-04",
        status: "Withdrawn",
        category: "Economia",
        supportLevel: 25,
        sources: [
          { label: "Senado \u2014 MP 1.227/2024", url: "https://www25.senado.leg.br/web/atividade/materias/-/materia/164093" }
        ]
      },
      {
        id: "pr15",
        title: "PEC da Seguran\xE7a P\xFAblica",
        description: "Proposta enviada ao Congresso para constitucionalizar o SUSP e ampliar compet\xEAncia da Uni\xE3o em seguran\xE7a; tramita\xE7\xE3o travada e baixa ades\xE3o de governadores.",
        dateProposed: "2024-10-31",
        status: "Active",
        category: "Seguran\xE7a",
        supportLevel: 35,
        sources: [
          { label: "C\xE2mara \u2014 PEC da Seguran\xE7a P\xFAblica", url: "https://www.camara.leg.br/noticias/1110050-governo-envia-pec-da-seguranca-publica-ao-congresso/" }
        ]
      },
      {
        id: "pr16",
        title: "Vetos derrubados pelo Congresso",
        description: "Conjunto de vetos presidenciais derrubados pelo Congresso em 2023\u20132024, incluindo Marco Temporal de Terras Ind\xEDgenas e trechos da desonera\xE7\xE3o da folha \u2014 sinal de derrotas pol\xEDticas relevantes para o Executivo.",
        dateProposed: "2023-12-14",
        status: "Failed",
        category: "Pol\xEDtica",
        supportLevel: 30,
        sources: [
          { label: "Congresso Nacional \u2014 Vetos", url: "https://www.congressonacional.leg.br/materias/vetos" }
        ]
      }
    ]
  },
  {
    id: "2",
    name: "Fl\xE1vio Bolsonaro",
    party: "PL",
    position: "Senador",
    state: "Rio de Janeiro",
    district: void 0,
    birthPlace: "Rio de Janeiro, RJ",
    mandates: [
      { position: "Deputado Estadual (RJ)", start: "2003", end: "2007" },
      { position: "Deputado Estadual (RJ)", start: "2007", end: "2011" },
      { position: "Deputado Estadual (RJ)", start: "2011", end: "2015" },
      { position: "Deputado Estadual (RJ)", start: "2015", end: "2019" },
      { position: "Senador (RJ)", start: "2019", end: "2027", current: true }
    ],
    termStart: "2019-02-01",
    termEnd: "2027-02-01",
    imageUrl: "",
    biography: "Fl\xE1vio Nantes Bolsonaro \xE9 um pol\xEDtico brasileiro, senador pelo estado do Rio de Janeiro desde 2019. Filho mais velho do ex-presidente Jair Bolsonaro, iniciou sua carreira pol\xEDtica como deputado estadual pelo Rio de Janeiro, cargo que exerceu por quatro mandatos consecutivos (2003-2019) na ALERJ. Como senador, tem atuado em pautas conservadoras, defesa da fam\xEDlia tradicional, seguran\xE7a p\xFAblica e liberalismo econ\xF4mico. \xC9 formado em Direito.",
    website: "https://www25.senado.leg.br/web/senadores/senador/-/perfil/4988",
    email: "sen.flaviobolsonaro@senado.leg.br",
    phone: "@flaviobolsonaro",
    committeeMemberships: ["Comiss\xE3o de Assuntos Econ\xF4micos (CAE)", "Comiss\xE3o de Constitui\xE7\xE3o, Justi\xE7a e Cidadania (CCJ)", "Comiss\xE3o de Seguran\xE7a P\xFAblica (CSP)"],
    voteRecords: [
      {
        id: "v4",
        title: "Reforma Tribut\xE1ria (PEC 45)",
        description: "Vota\xE7\xE3o em segundo turno no Senado da PEC da Reforma Tribut\xE1ria sobre o consumo.",
        date: "2023-11-08",
        vote: "No",
        billNumber: "PEC 45/2019",
        category: "Economia",
        sources: [
          { label: "Senado \u2014 Tramita\xE7\xE3o PEC 45/2019", url: "https://www25.senado.leg.br/web/atividade/materias/-/materia/137699" }
        ]
      },
      {
        id: "v5",
        title: "Marco Legal das Armas",
        description: "Projeto que flexibiliza regras para posse e porte de armas de fogo.",
        date: "2023-06-15",
        vote: "Yes",
        billNumber: "PL 3723/2019",
        category: "Seguran\xE7a P\xFAblica",
        sources: [
          { label: "Senado \u2014 PL 3723/2019", url: "https://www25.senado.leg.br/web/atividade/materias/-/materia/137357" }
        ]
      },
      {
        id: "v5b",
        title: "Novo Arcabou\xE7o Fiscal",
        description: "Vota\xE7\xE3o no Senado do novo marco fiscal proposto pelo governo Lula.",
        date: "2023-08-22",
        vote: "No",
        billNumber: "PLP 93/2023",
        category: "Economia",
        sources: [
          { label: "Senado \u2014 PLP 93/2023", url: "https://www25.senado.leg.br/web/atividade/materias/-/materia/158040" }
        ]
      },
      {
        id: "v22",
        title: "PEC do Estouro Fiscal de Transi\xE7\xE3o",
        description: "PEC que abriu espa\xE7o fiscal de R$ 145 bi fora do teto de gastos para o in\xEDcio do governo Lula.",
        date: "2022-12-21",
        vote: "No",
        billNumber: "PEC 32/2022",
        category: "Economia",
        sources: [
          { label: "Senado \u2014 PEC 32/2022", url: "https://www25.senado.leg.br/web/atividade/materias/-/materia/156003" }
        ]
      },
      {
        id: "v23",
        title: "Marco Temporal Ind\xEDgena",
        description: "Vota\xE7\xE3o do projeto que estabelece marco temporal para demarca\xE7\xE3o de terras ind\xEDgenas.",
        date: "2023-09-27",
        vote: "Yes",
        billNumber: "PL 2903/2023",
        category: "Meio Ambiente",
        sources: [
          { label: "Senado \u2014 PL 2903/2023", url: "https://www25.senado.leg.br/web/atividade/materias/-/materia/158738" }
        ]
      },
      {
        id: "v24",
        title: "Taxa\xE7\xE3o de Fundos Exclusivos e Offshores",
        description: "Vota\xE7\xE3o da lei que tributa rendimentos de fundos exclusivos e investimentos no exterior.",
        date: "2023-11-29",
        vote: "No",
        billNumber: "PL 4173/2023",
        category: "Economia",
        sources: [
          { label: "Senado \u2014 PL 4173/2023", url: "https://www25.senado.leg.br/web/atividade/materias/-/materia/160250" }
        ]
      },
      {
        id: "v25",
        title: "Saidinhas de Presos",
        description: "Vota\xE7\xE3o que restringe as sa\xEDdas tempor\xE1rias de presos do regime semiaberto.",
        date: "2024-04-09",
        vote: "Yes",
        billNumber: "PL 2253/2022",
        category: "Seguran\xE7a P\xFAblica",
        sources: [
          { label: "Senado \u2014 PL 2253/2022", url: "https://www25.senado.leg.br/web/atividade/materias/-/materia/154886" }
        ]
      },
      {
        id: "v26",
        title: "Regulamenta\xE7\xE3o da Reforma Tribut\xE1ria",
        description: "Vota\xE7\xE3o do PLP que regulamenta a Reforma Tribut\xE1ria (CBS/IBS).",
        date: "2024-12-12",
        vote: "No",
        billNumber: "PLP 68/2024",
        category: "Economia",
        sources: [
          { label: "Senado \u2014 PLP 68/2024", url: "https://www25.senado.leg.br/web/atividade/materias/-/materia/164914" }
        ]
      }
    ],
    promises: [
      {
        id: "p4",
        title: "Redu\xE7\xE3o de Impostos",
        description: "Lutar pela redu\xE7\xE3o da carga tribut\xE1ria sobre empresas e cidad\xE3os brasileiros.",
        datePromised: "2018-08-15",
        deadline: "2027-01-31",
        status: "In Progress",
        progress: 30,
        category: "Economia",
        sources: [
          { label: "Senado \u2014 Atividade do Senador", url: "https://www25.senado.leg.br/web/senadores/senador/-/perfil/4988" }
        ]
      },
      {
        id: "p5",
        title: "Endurecimento de Penas",
        description: "Defender o endurecimento de penas para crimes violentos e o direito \xE0 leg\xEDtima defesa armada.",
        datePromised: "2018-08-15",
        deadline: "2027-01-31",
        status: "In Progress",
        progress: 50,
        category: "Seguran\xE7a P\xFAblica",
        sources: [
          { label: "Senado \u2014 Projetos do Senador", url: "https://www25.senado.leg.br/web/atividade/materias/-/materias/pesquisa/lista?p_autor=4988" }
        ]
      },
      {
        id: "p5b",
        title: "Combate \xE0 Corrup\xE7\xE3o",
        description: "Apoiar projetos que fortale\xE7am o combate \xE0 corrup\xE7\xE3o e a transpar\xEAncia p\xFAblica.",
        datePromised: "2018-08-15",
        deadline: "2027-01-31",
        status: "In Progress",
        progress: 25,
        category: "Governan\xE7a",
        sources: [
          { label: "Senado \u2014 Atividade do Senador", url: "https://www25.senado.leg.br/web/senadores/senador/-/perfil/4988" }
        ]
      },
      {
        id: "p20",
        title: "Defesa da Fam\xEDlia Tradicional",
        description: "Defender em plen\xE1rio e nas comiss\xF5es pautas conservadoras ligadas \xE0 fam\xEDlia.",
        datePromised: "2018-08-15",
        deadline: "2027-01-31",
        status: "In Progress",
        progress: 65,
        category: "Costumes",
        sources: [
          { label: "Senado \u2014 Atividade do Senador", url: "https://www25.senado.leg.br/web/senadores/senador/-/perfil/4988" }
        ]
      },
      {
        id: "p21",
        title: "Privatiza\xE7\xF5es Estrat\xE9gicas",
        description: "Apoiar a privatiza\xE7\xE3o de estatais n\xE3o estrat\xE9gicas e desestatiza\xE7\xE3o da economia.",
        datePromised: "2018-08-15",
        deadline: "2027-01-31",
        status: "In Progress",
        progress: 35,
        category: "Economia",
        sources: [
          { label: "Senado \u2014 Atividade do Senador", url: "https://www25.senado.leg.br/web/senadores/senador/-/perfil/4988" }
        ]
      },
      {
        id: "p22",
        title: "Excludente de Ilicitude para Pol\xEDcias",
        description: "Aprovar o excludente de ilicitude para agentes de seguran\xE7a em opera\xE7\xF5es.",
        datePromised: "2018-08-15",
        deadline: "2027-01-31",
        status: "In Progress",
        progress: 30,
        category: "Seguran\xE7a P\xFAblica",
        sources: [
          { label: "Senado \u2014 Atividade do Senador", url: "https://www25.senado.leg.br/web/senadores/senador/-/perfil/4988" }
        ]
      }
    ],
    proposals: [
      {
        id: "pr3",
        title: "Escola sem Partido",
        description: "Projeto que visa garantir a neutralidade pol\xEDtico-ideol\xF3gica nas escolas.",
        dateProposed: "2023-03-20",
        status: "Active",
        category: "Educa\xE7\xE3o",
        supportLevel: 48,
        sources: [
          { label: "Senado \u2014 Atividade Legislativa", url: "https://www25.senado.leg.br/web/atividade/materias/-/materias/pesquisa/lista?p_autor=4988" }
        ]
      },
      {
        id: "pr3b",
        title: "Excludente de Ilicitude para Policiais",
        description: "Projeto que amplia a excludente de ilicitude para agentes de seguran\xE7a em opera\xE7\xF5es.",
        dateProposed: "2023-05-10",
        status: "Active",
        category: "Seguran\xE7a P\xFAblica",
        supportLevel: 42,
        sources: [
          { label: "Senado \u2014 Atividade Legislativa", url: "https://www25.senado.leg.br/web/atividade/materias/-/materias/pesquisa/lista?p_autor=4988" }
        ]
      },
      {
        id: "pr14",
        title: "CPI dos Atos de 8 de Janeiro \u2014 Voto Vencido",
        description: "Atua\xE7\xE3o na CPMI do 8 de Janeiro com posicionamento contr\xE1rio ao relat\xF3rio final.",
        dateProposed: "2023-10-17",
        status: "Failed",
        category: "Pol\xEDtica",
        supportLevel: 30,
        sources: [
          { label: "Senado \u2014 CPMI 8 de Janeiro", url: "https://legis.senado.leg.br/comissoes/comissao?codcol=2606" }
        ]
      },
      {
        id: "pr15",
        title: "Suspens\xE3o da Cobran\xE7a de Saidinhas",
        description: "Projeto para restringir sa\xEDdas tempor\xE1rias de presos condenados por crimes hediondos.",
        dateProposed: "2024-04-09",
        status: "Passed",
        category: "Seguran\xE7a P\xFAblica",
        supportLevel: 72,
        sources: [
          { label: "Planalto \u2014 Lei 14.843/2024", url: "https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2024/lei/L14843.htm" }
        ]
      }
    ]
  },
  {
    id: "3",
    name: "Ana Beatriz Costa",
    party: "MDB",
    position: "Deputada Estadual",
    state: "Rio de Janeiro",
    district: void 0,
    birthPlace: "Niter\xF3i, RJ",
    mandates: [
      { position: "Vereadora (Niter\xF3i)", start: "2017", end: "2021" },
      { position: "Deputada Estadual (RJ)", start: "2023", end: "2027", current: true }
    ],
    termStart: "2023-02-01",
    termEnd: "2027-02-01",
    imageUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop",
    biography: "Ana Beatriz Costa \xE9 Deputada Estadual pelo Rio de Janeiro, com forte atua\xE7\xE3o em educa\xE7\xE3o, sa\xFAde p\xFAblica e habita\xE7\xE3o popular. Iniciou sua trajet\xF3ria pol\xEDtica como vereadora em Niter\xF3i (2017-2021) antes de se eleger para a Assembleia Legislativa (ALERJ). Defende pol\xEDticas p\xFAblicas baseadas em dados e participa\xE7\xE3o cidad\xE3.",
    website: "https://www.alerj.rj.gov.br",
    email: "anabeatriz@alerj.rj.gov.br",
    phone: "@anabeatrizcosta",
    committeeMemberships: ["Comiss\xE3o de Educa\xE7\xE3o", "Comiss\xE3o de Sa\xFAde", "Comiss\xE3o de Habita\xE7\xE3o"],
    voteRecords: [
      {
        id: "v6",
        title: "Lei do Transporte P\xFAblico",
        description: "Reforma do sistema de transporte p\xFAblico no estado do RJ.",
        date: "2023-08-15",
        vote: "Yes",
        billNumber: "PL 1234/2023",
        category: "Transporte"
      },
      {
        id: "v7",
        title: "Programa Estadual de Habita\xE7\xE3o",
        description: "Cria\xE7\xE3o de programa para habita\xE7\xE3o popular no estado.",
        date: "2023-09-22",
        vote: "Yes",
        billNumber: "PL 2345/2023",
        category: "Habita\xE7\xE3o"
      },
      {
        id: "v8",
        title: "Aumento Salarial dos Professores",
        description: "Reajuste salarial para professores da rede estadual.",
        date: "2023-11-10",
        vote: "Yes",
        billNumber: "PL 3456/2023",
        category: "Educa\xE7\xE3o"
      }
    ],
    promises: [
      {
        id: "p6",
        title: "Investimento em Educa\xE7\xE3o P\xFAblica",
        description: "Aumentar em 30% o investimento em educa\xE7\xE3o p\xFAblica estadual.",
        datePromised: "2022-10-30",
        deadline: "2026-12-31",
        status: "In Progress",
        progress: 65,
        category: "Educa\xE7\xE3o"
      },
      {
        id: "p7",
        title: "Programa Habitacional",
        description: "Construir 5.000 unidades habitacionais para fam\xEDlias de baixa renda.",
        datePromised: "2022-10-30",
        deadline: "2026-12-31",
        status: "In Progress",
        progress: 55,
        category: "Habita\xE7\xE3o"
      }
    ],
    proposals: [
      {
        id: "pr4",
        title: "Valoriza\xE7\xE3o do Professor",
        description: "Projeto para aumentar sal\xE1rios e benef\xEDcios dos professores.",
        dateProposed: "2023-09-12",
        status: "Active",
        category: "Educa\xE7\xE3o",
        supportLevel: 71
      }
    ]
  },
  {
    id: "4",
    name: "Ronaldo Caiado",
    party: "Uni\xE3o Brasil",
    position: "Governador",
    state: "Goi\xE1s",
    district: void 0,
    birthPlace: "An\xE1polis, GO",
    mandates: [
      { position: "Senador (GO)", start: "1991", end: "1995" },
      { position: "Deputado Federal (GO)", start: "1999", end: "2003" },
      { position: "Deputado Federal (GO)", start: "2003", end: "2007" },
      { position: "Deputado Federal (GO)", start: "2007", end: "2011" },
      { position: "Deputado Federal (GO)", start: "2011", end: "2015" },
      { position: "Senador (GO)", start: "2015", end: "2019" },
      { position: "Governador de Goi\xE1s", start: "2019", end: "2023" },
      { position: "Governador de Goi\xE1s", start: "2023", end: "2027", current: true }
    ],
    termStart: "2023-01-01",
    termEnd: "2027-01-01",
    imageUrl: "",
    biography: "Ronaldo Ramos Caiado \xE9 m\xE9dico e pol\xEDtico brasileiro, atual Governador de Goi\xE1s em seu segundo mandato (2023-2027). Nascido em An\xE1polis (GO) em 1949, formou-se em Medicina pela UFG. Foi presidente da UDR nos anos 1980. Elegeu-se senador por Goi\xE1s em 1990 e deputado federal em 1998, 2002, 2006 e 2010. Foi novamente senador entre 2015 e 2018, quando se elegeu governador. \xC9 considerado uma lideran\xE7a do agroneg\xF3cio. Seu governo prioriza seguran\xE7a p\xFAblica, infraestrutura e desenvolvimento econ\xF4mico do estado.",
    website: "https://www.goias.gov.br",
    email: "governador@goias.gov.br",
    phone: "@ronaldocaiado",
    committeeMemberships: ["Cons\xF3rcio Brasil Central", "F\xF3rum de Governadores"],
    voteRecords: [
      {
        id: "v9",
        title: "Reforma Administrativa do Estado",
        description: "Reestrutura\xE7\xE3o das secretarias e \xF3rg\xE3os do governo estadual para maior efici\xEAncia.",
        date: "2023-03-15",
        vote: "Yes",
        billNumber: "Lei 21.792/2023",
        category: "Administra\xE7\xE3o",
        sources: [
          { label: "ALEGO \u2014 Leis Sancionadas", url: "https://portal.al.go.leg.br/leis" }
        ]
      },
      {
        id: "v10",
        title: "Programa Goi\xE1s Social",
        description: "Amplia\xE7\xE3o de programas de transfer\xEAncia de renda e assist\xEAncia social.",
        date: "2023-06-20",
        vote: "Yes",
        billNumber: "Lei 21.850/2023",
        category: "Social",
        sources: [
          { label: "Goi\xE1s Social \u2014 gov.br", url: "https://www.social.go.gov.br/goias-social" }
        ]
      },
      {
        id: "v11",
        title: "Incentivos ao Agroneg\xF3cio",
        description: "Pacote de incentivos fiscais para o setor agropecu\xE1rio goiano.",
        date: "2023-09-10",
        vote: "Yes",
        billNumber: "Decreto 10.234/2023",
        category: "Agroneg\xF3cio",
        sources: [
          { label: "SEFAZ-GO \u2014 Legisla\xE7\xE3o", url: "https://appasp.economia.go.gov.br/legislacao/arquivos/Superintendencia/SGAF/DECRETO/D_10234_023.htm" }
        ]
      },
      {
        id: "v27",
        title: "Universaliza\xE7\xE3o do Saneamento",
        description: "Marco regulat\xF3rio do saneamento b\xE1sico no estado de Goi\xE1s.",
        date: "2023-11-28",
        vote: "Yes",
        billNumber: "Lei 22.193/2023",
        category: "Saneamento",
        sources: [
          { label: "Goi\xE1s \u2014 Saneamento", url: "https://www.goias.gov.br/category/governo/saneamento/" }
        ]
      },
      {
        id: "v28",
        title: "Programa CRAS Bem Perto",
        description: "Amplia\xE7\xE3o da rede de Centros de Refer\xEAncia da Assist\xEAncia Social no estado.",
        date: "2024-02-14",
        vote: "Yes",
        billNumber: "Decreto 10.418/2024",
        category: "Social",
        sources: [
          { label: "Casa Civil GO \u2014 Decretos", url: "https://legisla.casacivil.go.gov.br/" }
        ]
      },
      {
        id: "v29",
        title: "Bolsa Estudo Universit\xE1ria",
        description: "Programa estadual de bolsas para estudantes do ensino superior.",
        date: "2024-05-22",
        vote: "Yes",
        billNumber: "Lei 22.554/2024",
        category: "Educa\xE7\xE3o",
        sources: [
          { label: "ALEGO \u2014 Leis", url: "https://portal.al.go.leg.br/leis" }
        ]
      },
      {
        id: "v30",
        title: "Opera\xE7\xE3o Tiradentes (Seguran\xE7a)",
        description: "Decreto que refor\xE7a opera\xE7\xF5es integradas de seguran\xE7a p\xFAblica em Goi\xE1s.",
        date: "2023-04-21",
        vote: "Yes",
        billNumber: "Decreto 10.156/2023",
        category: "Seguran\xE7a",
        sources: [
          { label: "SSP-GO", url: "https://www.policiacivil.go.gov.br/" }
        ]
      }
    ],
    promises: [
      {
        id: "p8",
        title: "Seguran\xE7a P\xFAblica Refor\xE7ada",
        description: "Reduzir a criminalidade em Goi\xE1s com investimento em pol\xEDcia e intelig\xEAncia.",
        datePromised: "2022-08-15",
        deadline: "2026-12-31",
        status: "Fulfilled",
        progress: 100,
        category: "Seguran\xE7a",
        sources: [
          { label: "SSP-GO \u2014 Estat\xEDsticas", url: "https://www.ssp.go.gov.br/estatistica" }
        ]
      },
      {
        id: "p9",
        title: "Goi\xE1s na Frente em Infraestrutura",
        description: "Asfaltar 10 mil km de estradas estaduais e municipais.",
        datePromised: "2022-08-15",
        deadline: "2026-12-31",
        status: "In Progress",
        progress: 65,
        category: "Infraestrutura",
        sources: [
          { label: "AGETOP \u2014 Goi\xE1s Estradeiro", url: "https://www.goinfra.go.gov.br/" }
        ]
      },
      {
        id: "p9b",
        title: "Equil\xEDbrio Fiscal do Estado",
        description: "Manter as contas do estado equilibradas sem aumento de impostos.",
        datePromised: "2022-08-15",
        deadline: "2026-12-31",
        status: "Fulfilled",
        progress: 100,
        category: "Economia",
        sources: [
          { label: "Tesouro Nacional \u2014 Capag GO", url: "https://www.tesourotransparente.gov.br/temas/estados-e-municipios/capacidade-de-pagamento-capag" }
        ]
      },
      {
        id: "p23",
        title: "Saneamento Universal",
        description: "Levar saneamento b\xE1sico a todos os munic\xEDpios goianos at\xE9 2026.",
        datePromised: "2022-08-15",
        deadline: "2026-12-31",
        status: "In Progress",
        progress: 55,
        category: "Saneamento",
        sources: [
          { label: "SNIS \u2014 Saneamento", url: "https://www.gov.br/cidades/pt-br/acesso-a-informacao/acoes-e-programas/saneamento/snis" }
        ]
      },
      {
        id: "p24",
        title: "Escolas em Tempo Integral",
        description: "Construir/converter 320 escolas em tempo integral at\xE9 o fim do mandato.",
        datePromised: "2022-08-15",
        deadline: "2026-12-31",
        status: "In Progress",
        progress: 65,
        category: "Educa\xE7\xE3o",
        sources: [
          { label: "Seduc-GO", url: "https://site.educacao.go.gov.br/" }
        ]
      },
      {
        id: "p25",
        title: "Cr\xE9dito Social (Aluguel Social)",
        description: "Conceder benef\xEDcio mensal de aluguel social para 100 mil fam\xEDlias.",
        datePromised: "2022-08-15",
        deadline: "2026-12-31",
        status: "In Progress",
        progress: 78,
        category: "Social",
        sources: [
          { label: "OVG \u2014 Aluguel Social", url: "https://www.social.go.gov.br/aluguel-social" }
        ]
      }
    ],
    proposals: [
      {
        id: "pr5",
        title: "Programa Servidor do Futuro",
        description: "Moderniza\xE7\xE3o e valoriza\xE7\xE3o do funcionalismo p\xFAblico estadual com capacita\xE7\xE3o e revis\xE3o salarial.",
        dateProposed: "2023-04-10",
        status: "Active",
        category: "Administra\xE7\xE3o",
        supportLevel: 68,
        sources: [
          { label: "SEAD-GO", url: "https://www.administracao.go.gov.br/" }
        ]
      },
      {
        id: "pr6",
        title: "Corredor Log\xEDstico Centro-Oeste",
        description: "Desenvolvimento de infraestrutura log\xEDstica para escoamento da produ\xE7\xE3o agr\xEDcola goiana.",
        dateProposed: "2023-07-22",
        status: "Passed",
        category: "Infraestrutura",
        supportLevel: 85,
        sources: [
          { label: "Goinfra", url: "https://www.goinfra.go.gov.br/" }
        ]
      },
      {
        id: "pr16",
        title: "Goi\xE1s Sem Fome",
        description: "Programa estadual de combate \xE0 inseguran\xE7a alimentar e nutricional.",
        dateProposed: "2024-03-18",
        status: "Passed",
        category: "Social",
        supportLevel: 88,
        sources: [
          { label: "OVG \u2014 Goi\xE1s Sem Fome", url: "https://www.ovg.org.br/post/goias-sem-fome" }
        ]
      },
      {
        id: "pr17",
        title: "Bolsa Pesquisa Goi\xE1s",
        description: "Concess\xE3o de bolsas para pesquisadores e mestrandos de institui\xE7\xF5es goianas.",
        dateProposed: "2024-06-12",
        status: "Active",
        category: "Educa\xE7\xE3o",
        supportLevel: 74,
        sources: [
          { label: "FAPEG", url: "https://www.fapeg.go.gov.br/" }
        ]
      }
    ]
  },
  {
    id: "5",
    name: "Renan Santos",
    party: "NOVO",
    position: "Deputado Federal",
    state: "S\xE3o Paulo",
    district: "S\xE3o Paulo",
    birthPlace: "S\xE3o Paulo, SP",
    mandates: [
      { position: "Deputado Federal (SP)", start: "2023", end: "2027", current: true }
    ],
    termStart: "2023-02-01",
    termEnd: "2027-01-31",
    imageUrl: "",
    biography: "Renan Haas Santos \xE9 empres\xE1rio, ativista pol\xEDtico e cofundador do Movimento Brasil Livre (MBL), uma das organiza\xE7\xF5es pol\xEDticas mais influentes do Brasil desde 2014. Tornou-se figura central nos protestos contra a corrup\xE7\xE3o e pelo impeachment de Dilma Rousseff em 2015-2016. Eleito Deputado Federal por S\xE3o Paulo em 2022, com foco em liberalismo econ\xF4mico, desburocratiza\xE7\xE3o do Estado e combate a privil\xE9gios no setor p\xFAblico.",
    website: "https://www.camara.leg.br/deputados/220552",
    email: "dep.renansantos@camara.leg.br",
    phone: "@renan_santos_mbl",
    committeeMemberships: ["Comiss\xE3o de Administra\xE7\xE3o e Servi\xE7o P\xFAblico", "Comiss\xE3o de Fiscaliza\xE7\xE3o Financeira e Controle", "Comiss\xE3o de Ci\xEAncia e Tecnologia"],
    voteRecords: [
      {
        id: "v12",
        title: "Reforma Tribut\xE1ria (PEC 45)",
        description: "Vota\xE7\xE3o na C\xE2mara da PEC da Reforma Tribut\xE1ria sobre o consumo.",
        date: "2023-07-07",
        vote: "Yes",
        billNumber: "PEC 45/2019",
        category: "Economia",
        sources: [
          { label: "C\xE2mara \u2014 PEC 45/2019", url: "https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2192459" }
        ]
      },
      {
        id: "v13",
        title: "Marco Legal das Garantias",
        description: "Lei que moderniza o sistema de garantias de cr\xE9dito no Brasil.",
        date: "2023-10-04",
        vote: "Yes",
        billNumber: "Lei 14.711/2023",
        category: "Economia",
        sources: [
          { label: "Planalto \u2014 Lei 14.711/2023", url: "https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2023/lei/L14711.htm" }
        ]
      },
      {
        id: "v14",
        title: "Novo Arcabou\xE7o Fiscal",
        description: "Vota\xE7\xE3o na C\xE2mara do novo marco fiscal do governo federal.",
        date: "2023-08-22",
        vote: "No",
        billNumber: "PLP 93/2023",
        category: "Economia",
        sources: [
          { label: "C\xE2mara \u2014 PLP 93/2023", url: "https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2356392" }
        ]
      },
      {
        id: "v31",
        title: "PEC do Estouro Fiscal de Transi\xE7\xE3o",
        description: "PEC que abriu R$ 145 bi fora do teto de gastos para o in\xEDcio do governo Lula.",
        date: "2022-12-22",
        vote: "No",
        billNumber: "PEC 32/2022",
        category: "Economia",
        sources: [
          { label: "C\xE2mara \u2014 PEC 32/2022", url: "https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2347043" }
        ]
      },
      {
        id: "v32",
        title: "Marco Temporal Ind\xEDgena (Derrubada do Veto)",
        description: "Vota\xE7\xE3o para derrubar o veto presidencial ao marco temporal ind\xEDgena.",
        date: "2023-12-14",
        vote: "Yes",
        billNumber: "PL 2903/2023",
        category: "Meio Ambiente",
        sources: [
          { label: "C\xE2mara \u2014 PL 2903/2023", url: "https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2370216" }
        ]
      },
      {
        id: "v33",
        title: "Taxa\xE7\xE3o de Fundos Exclusivos",
        description: "Lei que tributa rendimentos de fundos exclusivos e investimentos no exterior (offshores).",
        date: "2023-10-25",
        vote: "No",
        billNumber: "PL 4173/2023",
        category: "Economia",
        sources: [
          { label: "C\xE2mara \u2014 PL 4173/2023", url: "https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2386067" }
        ]
      },
      {
        id: "v34",
        title: "Regulamenta\xE7\xE3o da Reforma Tribut\xE1ria",
        description: "Vota\xE7\xE3o do PLP que regulamenta a Reforma Tribut\xE1ria (CBS/IBS).",
        date: "2024-07-10",
        vote: "Yes",
        billNumber: "PLP 68/2024",
        category: "Economia",
        sources: [
          { label: "C\xE2mara \u2014 PLP 68/2024", url: "https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2434742" }
        ]
      },
      {
        id: "v35",
        title: "PL das Fake News",
        description: "Projeto de regula\xE7\xE3o de plataformas digitais e modera\xE7\xE3o de conte\xFAdo.",
        date: "2023-04-25",
        vote: "No",
        billNumber: "PL 2630/2020",
        category: "Direitos Digitais",
        sources: [
          { label: "C\xE2mara \u2014 PL 2630/2020", url: "https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2256735" }
        ]
      }
    ],
    promises: [
      {
        id: "p10",
        title: "Redu\xE7\xE3o da M\xE1quina P\xFAblica",
        description: "Propor cortes em cargos comissionados e fun\xE7\xF5es de confian\xE7a no governo federal.",
        datePromised: "2022-08-15",
        deadline: "2027-01-31",
        status: "In Progress",
        progress: 40,
        category: "Administra\xE7\xE3o P\xFAblica",
        sources: [
          { label: "C\xE2mara \u2014 Atividade do Deputado", url: "https://www.camara.leg.br/deputados/220552" }
        ]
      },
      {
        id: "p11",
        title: "Combate a Privil\xE9gios",
        description: "Projetos para acabar com penduricalhos salariais e privil\xE9gios no setor p\xFAblico.",
        datePromised: "2022-08-15",
        deadline: "2027-01-31",
        status: "In Progress",
        progress: 55,
        category: "Transpar\xEAncia",
        sources: [
          { label: "C\xE2mara \u2014 Proposi\xE7\xF5es do Deputado", url: "https://www.camara.leg.br/deputados/220552?ano=2024" }
        ]
      },
      {
        id: "p12",
        title: "Desburocratiza\xE7\xE3o Digital",
        description: "Digitalizar e simplificar processos burocr\xE1ticos para cidad\xE3os e empresas.",
        datePromised: "2022-08-15",
        deadline: "2027-01-31",
        status: "In Progress",
        progress: 35,
        category: "Tecnologia",
        sources: [
          { label: "C\xE2mara \u2014 Atividade do Deputado", url: "https://www.camara.leg.br/deputados/220552" }
        ]
      },
      {
        id: "p26",
        title: "Fim do Foro Privilegiado",
        description: "Apresentar e apoiar PEC para extin\xE7\xE3o do foro privilegiado para pol\xEDticos.",
        datePromised: "2022-08-15",
        deadline: "2027-01-31",
        status: "In Progress",
        progress: 30,
        category: "Justi\xE7a",
        sources: [
          { label: "C\xE2mara \u2014 PECs em tramita\xE7\xE3o", url: "https://www.camara.leg.br/buscaProposicoesWeb/" }
        ]
      },
      {
        id: "p27",
        title: "Redu\xE7\xE3o de Impostos",
        description: "Defender redu\xE7\xE3o da carga tribut\xE1ria e simplifica\xE7\xE3o para PMEs.",
        datePromised: "2022-08-15",
        deadline: "2027-01-31",
        status: "In Progress",
        progress: 35,
        category: "Economia",
        sources: [
          { label: "C\xE2mara \u2014 Atividade do Deputado", url: "https://www.camara.leg.br/deputados/220552" }
        ]
      },
      {
        id: "p28",
        title: "Privatiza\xE7\xF5es Estrat\xE9gicas",
        description: "Apoiar privatiza\xE7\xE3o de estatais n\xE3o estrat\xE9gicas e desestatiza\xE7\xE3o.",
        datePromised: "2022-08-15",
        deadline: "2027-01-31",
        status: "In Progress",
        progress: 25,
        category: "Economia",
        sources: [
          { label: "C\xE2mara \u2014 Atividade do Deputado", url: "https://www.camara.leg.br/deputados/220552" }
        ]
      }
    ],
    proposals: [
      {
        id: "pr7",
        title: "Fim do Foro Privilegiado",
        description: "Proposta para extinguir o foro privilegiado para pol\xEDticos em exerc\xEDcio de mandato.",
        dateProposed: "2024-03-01",
        status: "Active",
        category: "Justi\xE7a",
        supportLevel: 78,
        sources: [
          { label: "C\xE2mara \u2014 Proposi\xE7\xF5es do Deputado", url: "https://www.camara.leg.br/deputados/220552?ano=2024" }
        ]
      },
      {
        id: "pr8",
        title: "Transpar\xEAncia Total nos Gastos P\xFAblicos",
        description: "Obrigatoriedade de publica\xE7\xE3o detalhada e em tempo real de todos os gastos com cart\xE3o corporativo e verbas parlamentares.",
        dateProposed: "2024-05-10",
        status: "Active",
        category: "Transpar\xEAncia",
        supportLevel: 85,
        sources: [
          { label: "C\xE2mara \u2014 Proposi\xE7\xF5es do Deputado", url: "https://www.camara.leg.br/deputados/220552?ano=2024" }
        ]
      },
      {
        id: "pr18",
        title: "Fim do Fundo Eleitoral",
        description: "Proposta para extinguir o financiamento p\xFAblico de campanhas eleitorais.",
        dateProposed: "2023-08-15",
        status: "Active",
        category: "Pol\xEDtica",
        supportLevel: 72,
        sources: [
          { label: "C\xE2mara \u2014 Proposi\xE7\xF5es do Deputado", url: "https://www.camara.leg.br/deputados/220552" }
        ]
      },
      {
        id: "pr19",
        title: "Limite a Sal\xE1rios no Servi\xE7o P\xFAblico",
        description: "Proposta para fixa\xE7\xE3o real do teto constitucional, eliminando penduricalhos.",
        dateProposed: "2024-09-04",
        status: "Active",
        category: "Administra\xE7\xE3o P\xFAblica",
        supportLevel: 68,
        sources: [
          { label: "C\xE2mara \u2014 Proposi\xE7\xF5es do Deputado", url: "https://www.camara.leg.br/deputados/220552?ano=2024" }
        ]
      }
    ]
  },
  {
    id: "6",
    name: "Romeu Zema",
    party: "NOVO",
    position: "Governador",
    state: "Minas Gerais",
    district: void 0,
    birthPlace: "Arax\xE1, MG",
    mandates: [
      { position: "Governador de Minas Gerais", start: "2019", end: "2023" },
      { position: "Governador de Minas Gerais", start: "2023", end: "2027", current: true }
    ],
    termStart: "2023-01-01",
    termEnd: "2027-01-01",
    imageUrl: "",
    biography: "Romeu Zema Neto \xE9 empres\xE1rio e pol\xEDtico brasileiro, atual Governador de Minas Gerais em seu segundo mandato (2023-2027). Nascido em Arax\xE1 (MG) em 1964, \xE9 formado em Engenharia Mec\xE2nica pela UFMG e administrou o Grupo Zema. Filiado ao partido NOVO, foi eleito governador em 2018 como outsider da pol\xEDtica. Reeleito em 2022 no primeiro turno com mais de 56% dos votos. Seu governo \xE9 marcado pelo foco em equil\xEDbrio fiscal, desburocratiza\xE7\xE3o, concess\xF5es e parcerias p\xFAblico-privadas.",
    website: "https://www.mg.gov.br",
    email: "governador@governo.mg.gov.br",
    phone: "@romeuzema",
    committeeMemberships: ["Cons\xF3rcio de Integra\xE7\xE3o Sul e Sudeste (COSUD)", "F\xF3rum de Governadores"],
    voteRecords: [
      {
        id: "v14b",
        title: "Reforma Administrativa de MG",
        description: "Reestrutura\xE7\xE3o do governo estadual com extin\xE7\xE3o e fus\xE3o de secretarias para redu\xE7\xE3o de gastos.",
        date: "2023-02-15",
        vote: "Yes",
        billNumber: "Lei 24.313/2023",
        category: "Administra\xE7\xE3o",
        sources: [
          { label: "ALMG \u2014 Lei 24.313/2023", url: "https://www.almg.gov.br/legislacao-mineira/lei/24313/2023/" }
        ]
      },
      {
        id: "v15",
        title: "Programa Minas Livre para Crescer",
        description: "Pacote de desburocratiza\xE7\xE3o e simplifica\xE7\xE3o tribut\xE1ria para empresas mineiras.",
        date: "2023-07-10",
        vote: "Yes",
        billNumber: "Lei 24.468/2023",
        category: "Economia",
        sources: [
          { label: "ALMG \u2014 Lei 24.468/2023", url: "https://www.almg.gov.br/legislacao-mineira/lei/24468/2023/" }
        ]
      },
      {
        id: "v15b",
        title: "Concess\xE3o de Rodovias Estaduais",
        description: "Aprova\xE7\xE3o de concess\xF5es rodovi\xE1rias para melhoria da malha vi\xE1ria de MG.",
        date: "2023-10-05",
        vote: "Yes",
        billNumber: "Decreto 48.765/2023",
        category: "Infraestrutura",
        sources: [
          { label: "IMA-MG \u2014 Concess\xF5es", url: "https://www.mg.gov.br/" }
        ]
      },
      {
        id: "v36",
        title: "Ades\xE3o ao Regime de Recupera\xE7\xE3o Fiscal",
        description: "Ades\xE3o de Minas Gerais ao RRF, com proposta de recupera\xE7\xE3o fiscal aprovada pela Uni\xE3o.",
        date: "2024-09-13",
        vote: "Yes",
        billNumber: "Lei 25.061/2024",
        category: "Economia",
        sources: [
          { label: "ALMG \u2014 Lei 25.061/2024", url: "https://www.almg.gov.br/legislacao-mineira/lei/25061/2024/" }
        ]
      },
      {
        id: "v37",
        title: "Privatiza\xE7\xE3o da Codemig",
        description: "Reestrutura\xE7\xE3o societ\xE1ria da Codemig com previs\xE3o de desestatiza\xE7\xE3o parcial.",
        date: "2023-08-30",
        vote: "Yes",
        billNumber: "Lei 24.491/2023",
        category: "Administra\xE7\xE3o",
        sources: [
          { label: "ALMG \u2014 Lei 24.491/2023", url: "https://www.almg.gov.br/legislacao-mineira/lei/24491/2023/" }
        ]
      },
      {
        id: "v38",
        title: "Programa Bolsa Merenda",
        description: "San\xE7\xE3o da lei que cria o Bolsa Merenda durante o recesso escolar.",
        date: "2023-12-14",
        vote: "Yes",
        billNumber: "Lei 24.683/2023",
        category: "Educa\xE7\xE3o",
        sources: [
          { label: "ALMG \u2014 Lei 24.683/2023", url: "https://www.almg.gov.br/legislacao-mineira/lei/24683/2023/" }
        ]
      },
      {
        id: "v39",
        title: "Acordo da Vale (Brumadinho)",
        description: "San\xE7\xE3o de acordo de repara\xE7\xE3o integral por danos do rompimento da barragem de Brumadinho.",
        date: "2021-02-04",
        vote: "Yes",
        billNumber: "Acordo Judicial Brumadinho",
        category: "Meio Ambiente",
        sources: [
          { label: "AGE-MG \u2014 Acordo Brumadinho", url: "https://www.agenciaminas.mg.gov.br/governador/biografia" }
        ]
      }
    ],
    promises: [
      {
        id: "p13",
        title: "Equil\xEDbrio Fiscal de Minas",
        description: "Recuperar as finan\xE7as do estado e eliminar o d\xE9ficit fiscal herdado.",
        datePromised: "2018-08-01",
        deadline: "2026-12-31",
        status: "Fulfilled",
        progress: 100,
        category: "Economia",
        sources: [
          { label: "Tesouro Nacional \u2014 Capag MG", url: "https://www.tesourotransparente.gov.br/temas/estados-e-municipios/capacidade-de-pagamento-capag" }
        ]
      },
      {
        id: "p14",
        title: "Pagar Servidores em Dia",
        description: "Regularizar o pagamento dos servidores p\xFAblicos estaduais sem atrasos.",
        datePromised: "2018-08-01",
        deadline: "2026-12-31",
        status: "Fulfilled",
        progress: 100,
        category: "Administra\xE7\xE3o",
        sources: [
          { label: "Portal da Transpar\xEAncia MG", url: "https://www.transparencia.mg.gov.br/" }
        ]
      },
      {
        id: "p15",
        title: "Concess\xF5es e PPPs",
        description: "Ampliar parcerias p\xFAblico-privadas para melhorar infraestrutura e servi\xE7os p\xFAblicos.",
        datePromised: "2018-08-01",
        deadline: "2026-12-31",
        status: "In Progress",
        progress: 70,
        category: "Infraestrutura",
        sources: [
          { label: "SEINFRA-MG", url: "https://www.infraestrutura.mg.gov.br/" }
        ]
      },
      {
        id: "p29",
        title: "Reforma Administrativa Estadual",
        description: "Reduzir o n\xFAmero de secretarias e cargos comissionados.",
        datePromised: "2018-08-01",
        deadline: "2023-12-31",
        status: "Fulfilled",
        progress: 100,
        category: "Administra\xE7\xE3o",
        sources: [
          { label: "ALMG \u2014 Lei 24.313/2023", url: "https://www.almg.gov.br/legislacao-mineira/lei/24313/2023/" }
        ]
      },
      {
        id: "p30",
        title: "Ades\xE3o ao Regime de Recupera\xE7\xE3o Fiscal",
        description: "Aderir ao RRF para resolver a d\xEDvida do estado com a Uni\xE3o.",
        datePromised: "2022-08-01",
        deadline: "2026-12-31",
        status: "Fulfilled",
        progress: 100,
        category: "Economia",
        sources: [
          { label: "STN \u2014 Regime de Recupera\xE7\xE3o Fiscal", url: "https://www.tesourotransparente.gov.br/temas/estados-e-municipios/regime-de-recuperacao-fiscal-rrf" }
        ]
      },
      {
        id: "p31",
        title: "Minas Digital",
        description: "Digitalizar 100% dos servi\xE7os p\xFAblicos estaduais at\xE9 2026.",
        datePromised: "2022-08-01",
        deadline: "2026-12-31",
        status: "In Progress",
        progress: 75,
        category: "Tecnologia",
        sources: [
          { label: "PRODEMGE \u2014 MG App", url: "https://www.prodemge.gov.br/" }
        ]
      }
    ],
    proposals: [
      {
        id: "pr9",
        title: "Minas Digital",
        description: "Digitaliza\xE7\xE3o completa dos servi\xE7os p\xFAblicos estaduais com atendimento 100% online via MG App.",
        dateProposed: "2023-05-20",
        status: "Active",
        category: "Tecnologia",
        supportLevel: 79,
        sources: [
          { label: "PRODEMGE", url: "https://www.prodemge.gov.br/" }
        ]
      },
      {
        id: "pr10",
        title: "Seguran\xE7a H\xEDdrica de MG",
        description: "Programa de recupera\xE7\xE3o de bacias hidrogr\xE1ficas e garantia de abastecimento de \xE1gua.",
        dateProposed: "2023-08-12",
        status: "Active",
        category: "Meio Ambiente",
        supportLevel: 76,
        sources: [
          { label: "IGAM \u2014 Recursos H\xEDdricos", url: "http://www.igam.mg.gov.br/" }
        ]
      },
      {
        id: "pr20",
        title: "Concess\xE3o das Rodovias do Sul/Sudoeste",
        description: "Concess\xE3o de pacotes rodovi\xE1rios para empresas privadas, com obriga\xE7\xE3o de duplica\xE7\xE3o e melhoria.",
        dateProposed: "2024-04-08",
        status: "Passed",
        category: "Infraestrutura",
        supportLevel: 80,
        sources: [
          { label: "SEINFRA \u2014 Concess\xF5es Rodovi\xE1rias", url: "https://www.infraestrutura.mg.gov.br/" }
        ]
      },
      {
        id: "pr21",
        title: "Privatiza\xE7\xE3o da Cemig",
        description: "Proposta de desestatiza\xE7\xE3o parcial da Cemig (energia el\xE9trica) para captar recursos e reduzir d\xEDvida.",
        dateProposed: "2024-10-15",
        status: "Active",
        category: "Energia",
        supportLevel: 52,
        sources: [
          { label: "Cemig \u2014 Rela\xE7\xF5es com Investidores", url: "https://ri.cemig.com.br/" }
        ]
      }
    ]
  }
];

// src/lib/mcp/politicians.ts
function listPoliticians() {
  return politiciansData.map((p) => ({
    id: p.id,
    name: p.name,
    party: p.party,
    position: p.position,
    state: p.state,
    termStart: p.termStart,
    termEnd: p.termEnd,
    instagram: p.phone,
    website: p.website,
    counts: {
      votes: p.voteRecords.length,
      promises: p.promises.length,
      proposals: p.proposals.length
    }
  }));
}
function findPolitician(query) {
  const q = query.trim().toLowerCase();
  return politiciansData.find((p) => p.id === q) ?? politiciansData.find((p) => p.name.toLowerCase() === q) ?? politiciansData.find((p) => p.name.toLowerCase().includes(q)) ?? politiciansData.find((p) => p.party.toLowerCase() === q);
}
function politicianDetail(query) {
  const p = findPolitician(query);
  if (!p) return void 0;
  const { imageUrl: _imageUrl, phone, ...rest } = p;
  return { ...rest, instagram: phone };
}
function listCommitments(query, status) {
  const people = query ? [findPolitician(query)].filter(Boolean) : politiciansData;
  const items = people.flatMap(
    (p) => [
      ...p.promises.map((pr) => ({ kind: "promessa", ...pr })),
      ...p.proposals.map((pp) => ({
        kind: "proposta",
        id: pp.id,
        title: pp.title,
        description: pp.description,
        datePromised: pp.dateProposed,
        deadline: "",
        status: pp.status,
        progress: pp.supportLevel,
        category: pp.category,
        sources: pp.sources
      }))
    ].map((item) => ({ politicianId: p.id, politicianName: p.name, ...item }))
  );
  return status ? items.filter((i) => i.status.toLowerCase() === status.trim().toLowerCase()) : items;
}
function platformStats() {
  return {
    politicians: politiciansData.length,
    votes: politiciansData.reduce((n, p) => n + p.voteRecords.length, 0),
    promises: politiciansData.reduce((n, p) => n + p.promises.length, 0),
    proposals: politiciansData.reduce((n, p) => n + p.proposals.length, 0)
  };
}

// src/lib/mcp/tools/list-politicians.ts
var list_politicians_default = defineTool({
  name: "list_politicians",
  title: "Listar pol\xEDticos",
  description: "Lista todos os pol\xEDticos monitorados na plataforma Polis, com partido, cargo, estado, mandato e contagem de votos, promessas e propostas.",
  inputSchema: {
    party: z.string().optional().describe("Filtrar por sigla do partido (ex.: PT, PL).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ party }) => {
    const all = listPoliticians();
    const items = party ? all.filter((p) => p.party.toLowerCase() === party.trim().toLowerCase()) : all;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { politicians: items }
    };
  }
});

// src/lib/mcp/tools/get-politician.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_politician_default = defineTool2({
  name: "get_politician",
  title: "Perfil do pol\xEDtico",
  description: "Retorna o perfil completo de um pol\xEDtico da Polis: biografia, mandatos, vota\xE7\xF5es, promessas e propostas, sempre com as fontes oficiais.",
  inputSchema: {
    politician: z2.string().describe("ID ou nome (parcial) do pol\xEDtico, ex.: 'Lula' ou '1'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ politician }) => {
    const data = politicianDetail(politician);
    if (!data) {
      return {
        content: [{ type: "text", text: `Nenhum pol\xEDtico encontrado para "${politician}".` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { politician: data }
    };
  }
});

// src/lib/mcp/tools/list-commitments.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_commitments_default = defineTool3({
  name: "list_commitments",
  title: "Promessas e propostas",
  description: "Lista promessas e propostas monitoradas pela Polis, com status (cumprida, em andamento, quebrada, etc.), progresso, categoria e fontes oficiais.",
  inputSchema: {
    politician: z3.string().optional().describe("ID ou nome (parcial) do pol\xEDtico. Sem valor, retorna de todos."),
    status: z3.string().optional().describe("Filtrar por status exato: Fulfilled, In Progress, Broken, Expired, Active, Passed, Failed, Withdrawn.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ politician, status }) => {
    const items = listCommitments(politician, status);
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { commitments: items }
    };
  }
});

// src/lib/mcp/tools/get-platform-stats.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
var get_platform_stats_default = defineTool4({
  name: "get_platform_stats",
  title: "Estat\xEDsticas da plataforma",
  description: "Retorna os n\xFAmeros atuais da Polis: pol\xEDticos monitorados, vota\xE7\xF5es registradas, promessas e propostas acompanhadas.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const stats = platformStats();
    return {
      content: [{ type: "text", text: JSON.stringify(stats, null, 2) }],
      structuredContent: stats
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "polis",
  title: "Polis",
  version: "0.1.0",
  instructions: "Ferramentas p\xFAblicas da Polis, plataforma brasileira de transpar\xEAncia pol\xEDtica. Use `list_politicians` para descobrir os pol\xEDticos monitorados, `get_politician` para o perfil completo (vota\xE7\xF5es, promessas e propostas com fontes), `list_commitments` para promessas e propostas com status e progresso, e `get_platform_stats` para os n\xFAmeros agregados da plataforma. Todos os dados citam fontes oficiais brasileiras.",
  tools: [list_politicians_default, get_politician_default, list_commitments_default, get_platform_stats_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
