// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-politicians.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";

// src/data/mockData.ts
import { politiciansData } from "npm:@/data/politiciansData";
import lulaImg from "npm:@/assets/politicians/lula.jpg";
import flavioImg from "npm:@/assets/politicians/flavio-bolsonaro.jpg";
import caiadoImg from "npm:@/assets/politicians/ronaldo-caiado.jpg";
import renanImg from "npm:@/assets/politicians/renan-santos.jpg";
import zemaImg from "npm:@/assets/politicians/romeu-zema.jpg";
var politicianImages = {
  "1": lulaImg,
  "2": flavioImg,
  "4": caiadoImg,
  "5": renanImg,
  "6": zemaImg
};
var mockPoliticians = politiciansData.map((p) => ({
  ...p,
  imageUrl: politicianImages[p.id] ?? p.imageUrl
}));

// src/data/legacyData.ts
import {
  GraduationCap,
  Stethoscope,
  ShieldCheck,
  Landmark,
  Droplets,
  BriefcaseBusiness,
  TrendingUp,
  FileText,
  Vote,
  Users,
  Leaf,
  Building2
} from "npm:lucide-react@^0.462.0";
var splitSeries = (values) => values.map((v) => ({
  ano: v.ano,
  Anterior: v.current ? null : v.value,
  Atual: v.current ? v.value : null
}));
var legacyDataMap = {
  // Lula - Presidente
  "1": {
    subtitle: "Indicadores nacionais consolidados ao longo dos tr\xEAs mandatos presidenciais de Lula (2003\u20132010 e 2023\u2013presente). Inclui avan\xE7os e retrocessos com fontes oficiais.",
    commitments: [
      // 1º e 2º mandatos (2003–2010) — promessas históricas cumpridas
      { id: 101, title: "Bolsa Fam\xEDlia (1\xBA mandato)", icon: Users, status: "Cumprida", progress: 100, detail: "Programa criado em 2003, unificou benef\xEDcios sociais e atendeu ~12 mi de fam\xEDlias at\xE9 2010.", sources: [{ label: "MDS \u2014 Hist\xF3rico do Bolsa Fam\xEDlia", url: "https://www.gov.br/mds/pt-br/acoes-e-programas/bolsa-familia" }] },
      { id: 102, title: "Pr\xE9-sal e explora\xE7\xE3o nacional (2\xBA mandato)", icon: Droplets, status: "Cumprida", progress: 100, detail: "Modelo de partilha aprovado (Lei 12.351/2010); cria\xE7\xE3o da PPSA.", sources: [{ label: "Planalto \u2014 Lei 12.351/2010", url: "https://www.planalto.gov.br/ccivil_03/_ato2007-2010/2010/lei/l12351.htm" }] },
      { id: 103, title: "ProUni e expans\xE3o das universidades federais", icon: GraduationCap, status: "Cumprida", progress: 100, detail: "ProUni criado em 2004 (Lei 11.096/2005); REUNI ampliou vagas em IFES a partir de 2007.", sources: [{ label: "Planalto \u2014 Lei 11.096/2005 (ProUni)", url: "https://www.planalto.gov.br/ccivil_03/_ato2004-2006/2005/lei/l11096.htm" }] },
      { id: 104, title: "Minha Casa Minha Vida \u2014 vers\xE3o original (2\xBA mandato)", icon: Building2, status: "Cumprida", progress: 100, detail: "Programa lan\xE7ado em 2009; mais de 1 mi de unidades contratadas at\xE9 2010.", sources: [{ label: "Caixa \u2014 Hist\xF3rico MCMV", url: "https://www.caixa.gov.br/voce/habitacao/minha-casa-minha-vida/Paginas/default.aspx" }] },
      // 3º mandato (2023–) — em andamento / cumpridas
      { id: 1, title: "Brasil Sem Fome (3\xBA mandato)", icon: Stethoscope, status: "Em Andamento", progress: 55, detail: "Sa\xEDda do Mapa da Fome da FAO em curso; inseguran\xE7a alimentar grave caiu para 8,7%.", sources: [{ label: "FAO \u2014 SOFI 2024", url: "https://www.fao.org/publications/sofi/2024/en/" }] },
      { id: 2, title: "Desmatamento Zero \u2014 Amaz\xF4nia (3\xBA mandato)", icon: Leaf, status: "Em Andamento", progress: 50, detail: "Queda de ~50% no desmatamento da Amaz\xF4nia entre 2022 e 2024.", sources: [{ label: "INPE \u2014 PRODES", url: "http://terrabrasilis.dpi.inpe.br/app/dashboard/deforestation/biomes/legal_amazon/rates" }] },
      { id: 3, title: "Reajuste real do sal\xE1rio m\xEDnimo (3\xBA mandato)", icon: BriefcaseBusiness, status: "Cumprida", progress: 100, detail: "Pol\xEDtica de valoriza\xE7\xE3o restabelecida (Lei 14.663/2023). M\xEDnimo: R$ 1.212 \u2192 R$ 1.518.", sources: [{ label: "Planalto \u2014 Lei 14.663/2023", url: "https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2023/lei/L14663.htm" }] },
      { id: 5, title: "Reforma Tribut\xE1ria (3\xBA mandato)", icon: Landmark, status: "Cumprida", progress: 100, detail: "Emenda Constitucional 132/2023 promulgada \u2014 unifica tributos sobre consumo.", sources: [{ label: "Planalto \u2014 EC 132/2023", url: "https://www.planalto.gov.br/ccivil_03/constituicao/emendas/emc/emc132.htm" }] },
      { id: 6, title: "Novo PAC (3\xBA mandato)", icon: BriefcaseBusiness, status: "Em Andamento", progress: 35, detail: "R$ 1,7 trilh\xE3o em investimentos previstos at\xE9 2026.", sources: [{ label: "Gov.br \u2014 Novo PAC", url: "https://www.gov.br/casacivil/pt-br/novopac" }] },
      // 3º mandato — promessas descumpridas / parciais
      { id: 201, title: "Isen\xE7\xE3o de IR at\xE9 R$ 5.000 (3\xBA mandato)", icon: Landmark, status: "N\xE3o Cumprida", progress: 40, detail: "Faixa de isen\xE7\xE3o subiu para ~R$ 2.824 (2 SM) em 2024 com ajustes graduais, mas R$ 5.000 ainda n\xE3o foi atingido at\xE9 maio/2026 devido ao alto custo fiscal.", sources: [{ label: "Receita Federal \u2014 IRPF", url: "https://www.gov.br/receitafederal/pt-br/assuntos/meu-imposto-de-renda" }, { label: "MP 1.171/2023 \u2014 reajuste IRPF", url: "https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2023/mpv/mpv1171.htm" }] },
      { id: 202, title: "Picanha e cervejinha na mesa (3\xBA mandato)", icon: Users, status: "Parcialmente Cumprida", progress: 50, detail: "Pre\xE7o da carne caiu 9\u201311% no IPCA de 2023 e o poder de compra subiu com infla\xE7\xE3o controlada, mas a 'fartura' prometida ficou no campo simb\xF3lico \u2014 sem distribui\xE7\xE3o direta nem queda generalizada sustentada.", sources: [{ label: "IBGE \u2014 IPCA", url: "https://www.ibge.gov.br/explica/inflacao.php" }] },
      { id: 203, title: "Zerar a fila do SUS (3\xBA mandato)", icon: Stethoscope, status: "N\xE3o Cumprida", progress: 25, detail: "Programa Agora Tem Especialistas lan\xE7ado em 2024, mas filas para cirurgias eletivas e exames seguem em milh\xF5es de procedimentos.", sources: [{ label: "Minist\xE9rio da Sa\xFAde", url: "https://www.gov.br/saude/pt-br" }, { label: "CONASS", url: "https://www.conass.org.br/" }] },
      { id: 204, title: "D\xE9ficit zero em 2024 (3\xBA mandato)", icon: TrendingUp, status: "N\xE3o Cumprida", progress: 10, detail: "Meta fiscal revisada de zero para -0,25% PIB; resultado prim\xE1rio fechou 2024 em d\xE9ficit de ~R$ 230 bi.", sources: [{ label: "Tesouro Nacional \u2014 RTN", url: "https://www.gov.br/tesouronacional/pt-br/estatisticas-fiscais-e-planejamento/resultado-do-tesouro-nacional" }] },
      { id: 205, title: "Reverter privatiza\xE7\xF5es (Eletrobras/Petrobras/Correios)", icon: Landmark, status: "Parcialmente Cumprida", progress: 35, detail: "Revers\xE3o da privatiza\xE7\xE3o da Eletrobras n\xE3o concretizada; Correios mantidos estatais; Petrobras com mudan\xE7a de governan\xE7a mas sem estatiza\xE7\xE3o adicional.", sources: [{ label: "BNDES \u2014 Desestatiza\xE7\xE3o", url: "https://www.bndes.gov.br/wps/portal/site/home/transparencia/desestatizacao" }] }
    ],
    performance: [
      {
        title: "Economia \u2014 1\xBA e 2\xBA mandatos (2003\u20132010)",
        icon: TrendingUp,
        metrics: [
          { label: "Crescimento m\xE9dio do PIB (a.a.)", before: "2,3%", after: "4,0%", change: "+1,7 p.p.", positive: true, sources: [{ label: "IBGE \u2014 Contas Nacionais", url: "https://www.ibge.gov.br/explica/pib.php" }, { label: "IPEADATA", url: "http://www.ipeadata.gov.br/" }] },
          { label: "Taxa de desemprego (PME)", before: "12,3%", after: "6,7%", change: "-5,6 p.p.", positive: true, sources: [{ label: "IBGE \u2014 Pesquisa Mensal de Emprego", url: "https://www.ibge.gov.br/estatisticas/sociais/trabalho/9180-pesquisa-mensal-de-emprego.html" }] },
          { label: "Empregos formais criados (CAGED, acumulado)", before: "\u2014", after: "~15 milh\xF5es", change: "Recorde hist\xF3rico", positive: true, sources: [{ label: "MTE \u2014 CAGED", url: "https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/estatisticas-trabalho/caged" }] },
          { label: "Reservas internacionais (US$ bi)", before: "37,8", after: "288,6", change: "+663%", positive: true, sources: [{ label: "BCB \u2014 Reservas Internacionais", url: "https://www.bcb.gov.br/estatisticas/reservas" }] },
          { label: "Sal\xE1rio m\xEDnimo real (ganho acumulado)", before: "\u2014", after: "+53,7%", change: "+53,7%", positive: true, sources: [{ label: "DIEESE \u2014 Sal\xE1rio M\xEDnimo", url: "https://www.dieese.org.br/analisecestabasica/salarioMinimo.html" }] },
          { label: "Carga tribut\xE1ria bruta (% PIB)", before: "32,0%", after: "33,5%", change: "+1,5 p.p.", positive: false, sources: [{ label: "Receita Federal \u2014 Carga Tribut\xE1ria", url: "https://www.gov.br/receitafederal/pt-br/centrais-de-conteudo/publicacoes/relatorios/carga-tributaria-no-brasil" }] },
          { label: "Infla\xE7\xE3o (IPCA, fim de 2010)", before: "5,69% (2002)", after: "5,91% (2010)", change: "Acima do centro da meta", positive: false, sources: [{ label: "IBGE \u2014 IPCA", url: "https://www.ibge.gov.br/explica/inflacao.php" }] },
          { label: "D\xEDvida L\xEDquida do Setor P\xFAblico (% PIB)", before: "60,4%", after: "38,0%", change: "-22,4 p.p.", positive: true, sources: [{ label: "BCB \u2014 Estat\xEDsticas Fiscais", url: "https://www.bcb.gov.br/estatisticas/estatisticasfiscais" }] }
        ]
      },
      {
        title: "Social \u2014 1\xBA e 2\xBA mandatos (2003\u20132010)",
        icon: Users,
        metrics: [
          { label: "Pobreza extrema (% pop.)", before: "12,0%", after: "5,2%", change: "-6,8 p.p.", positive: true, sources: [{ label: "IPEA \u2014 Pobreza e Desigualdade", url: "https://www.ipea.gov.br/portal/" }] },
          { label: "Fam\xEDlias atendidas pelo Bolsa Fam\xEDlia (mi)", before: "3,6", after: "12,8", change: "+255%", positive: true, sources: [{ label: "MDS \u2014 Bolsa Fam\xEDlia", url: "https://www.gov.br/mds/pt-br/acoes-e-programas/bolsa-familia" }] },
          { label: "IDH (Brasil)", before: "0,710", after: "0,727", change: "+0,017", positive: true, sources: [{ label: "PNUD \u2014 IDH", url: "https://www.undp.org/pt/brazil" }] },
          { label: "Mortalidade infantil (por mil nasc.)", before: "27,4", after: "16,2", change: "-40,9%", positive: true, sources: [{ label: "DATASUS", url: "https://datasus.saude.gov.br/" }] },
          { label: "\xCDndice de Gini", before: "0,583", after: "0,533", change: "-0,050", positive: true, sources: [{ label: "IBGE \u2014 PNAD", url: "https://www.ibge.gov.br/" }] },
          { label: "Taxa de homic\xEDdios (por 100 mil)", before: "28,5", after: "27,4", change: "-1,1", positive: false, sources: [{ label: "IPEA \u2014 Atlas da Viol\xEAncia", url: "https://www.ipea.gov.br/atlasviolencia/" }] }
        ]
      },
      {
        title: "Economia \u2014 3\xBA mandato (2023\u2013presente)",
        icon: TrendingUp,
        metrics: [
          { label: "Crescimento do PIB", before: "2,9%", after: "3,2%", change: "+0,3 p.p.", positive: true, sources: [{ label: "IBGE \u2014 Contas Nacionais", url: "https://www.ibge.gov.br/explica/pib.php" }] },
          { label: "Taxa de desemprego", before: "8,5%", after: "6,2%", change: "-2,3 p.p.", positive: true, sources: [{ label: "IBGE \u2014 PNAD Cont\xEDnua", url: "https://www.ibge.gov.br/estatisticas/sociais/trabalho/9173-pesquisa-nacional-por-amostra-de-domicilios-continua-trimestral.html" }] },
          { label: "Infla\xE7\xE3o (IPCA acumulado)", before: "5,79%", after: "4,83%", change: "-0,96 p.p.", positive: true, sources: [{ label: "IBGE \u2014 IPCA", url: "https://www.ibge.gov.br/explica/inflacao.php" }] },
          { label: "Sal\xE1rio M\xEDnimo (R$)", before: "R$ 1.212", after: "R$ 1.518", change: "+25,2%", positive: true, sources: [{ label: "Planalto \u2014 Lei 14.663/2023", url: "https://www.planalto.gov.br/ccivil_03/_ato2023-2026/2023/lei/L14663.htm" }] },
          { label: "D\xEDvida P\xFAblica Bruta (% PIB)", before: "71,7%", after: "76,5%", change: "+4,8 p.p.", positive: false, sources: [{ label: "BCB \u2014 Estat\xEDsticas Fiscais", url: "https://www.bcb.gov.br/estatisticas/estatisticasfiscais" }] },
          { label: "Taxa Selic (a.a.)", before: "13,75%", after: "15,00%", change: "+1,25 p.p.", positive: false, sources: [{ label: "BCB \u2014 Hist\xF3rico Selic / Copom", url: "https://www.bcb.gov.br/controleinflacao/historicotaxasjuros" }] },
          { label: "Resultado Prim\xE1rio (R$ bi)", before: "+54,1", after: "-230,5", change: "Revers\xE3o de super\xE1vit para d\xE9ficit", positive: false, sources: [{ label: "Tesouro Nacional \u2014 RTN", url: "https://www.gov.br/tesouronacional/pt-br/estatisticas-fiscais-e-planejamento/resultado-do-tesouro-nacional" }] },
          { label: "C\xE2mbio R$/US$ (m\xE9dia anual)", before: "R$ 5,16", after: "R$ 5,39", change: "+4,5%", positive: false, sources: [{ label: "BCB \u2014 PTAX", url: "https://www.bcb.gov.br/estabilidadefinanceira/historicocotacoes" }] }
        ]
      },
      {
        title: "Social \u2014 3\xBA mandato (2023\u2013presente)",
        icon: Users,
        metrics: [
          { label: "Pobreza extrema", before: "5,9%", after: "4,4%", change: "-1,5 p.p.", positive: true, sources: [{ label: "IBGE \u2014 S\xEDntese de Indicadores Sociais", url: "https://www.ibge.gov.br/estatisticas/sociais/populacao/9221-sintese-de-indicadores-sociais.html" }] },
          { label: "Inseguran\xE7a alimentar grave", before: "15,5%", after: "8,7%", change: "-6,8 p.p.", positive: true, sources: [{ label: "FAO \u2014 SOFI 2024", url: "https://www.fao.org/publications/sofi/2024/en/" }] },
          { label: "Fam\xEDlias no Bolsa Fam\xEDlia (mi)", before: "21,1", after: "20,5", change: "-0,6", positive: true, sources: [{ label: "MDS \u2014 Bolsa Fam\xEDlia", url: "https://www.gov.br/mds/pt-br/acoes-e-programas/bolsa-familia" }] },
          { label: "Aprova\xE7\xE3o do governo (\xF3timo/bom)", before: "38%", after: "24%", change: "-14 p.p.", positive: false, sources: [{ label: "Datafolha \u2014 Avalia\xE7\xE3o do Governo Lula", url: "https://datafolha.folha.uol.com.br/" }] },
          { label: "Homic\xEDdios (por 100 mil hab.)", before: "22,8", after: "23,4", change: "+0,6", positive: false, sources: [{ label: "FBSP \u2014 Anu\xE1rio 2024", url: "https://forumseguranca.org.br/anuario-brasileiro-seguranca-publica/" }] }
        ]
      },
      {
        title: "Meio Ambiente \u2014 compara\xE7\xE3o hist\xF3rica (1\xBA/2\xBA vs 3\xBA mandato)",
        icon: Leaf,
        metrics: [
          { label: "Desmatamento Amaz\xF4nia \u2014 2\xBA mandato (2004 \u2192 2010)", before: "27.772 km\xB2", after: "7.000 km\xB2", change: "-74,8%", positive: true, sources: [{ label: "INPE \u2014 PRODES", url: "http://terrabrasilis.dpi.inpe.br/app/dashboard/deforestation/biomes/legal_amazon/rates" }] },
          { label: "Desmatamento Amaz\xF4nia \u2014 3\xBA mandato (2022 \u2192 2024)", before: "11.594 km\xB2", after: "5.816 km\xB2", change: "-49,8%", positive: true, sources: [{ label: "INPE \u2014 PRODES", url: "http://terrabrasilis.dpi.inpe.br/app/dashboard/deforestation/biomes/legal_amazon/rates" }] },
          { label: "Desmatamento Cerrado \u2014 3\xBA mandato", before: "10.689 km\xB2", after: "8.174 km\xB2", change: "-23,5%", positive: true, sources: [{ label: "INPE \u2014 PRODES Cerrado", url: "http://terrabrasilis.dpi.inpe.br/app/dashboard/deforestation/biomes/cerrado/rates" }] },
          { label: "Focos de queimada no Pantanal \u2014 3\xBA mandato", before: "8.182", after: "12.581", change: "+53,8%", positive: false, sources: [{ label: "INPE \u2014 Programa Queimadas", url: "https://terrabrasilis.dpi.inpe.br/queimadas/situacao-atual/" }] },
          { label: "\xC1rea queimada no Brasil \u2014 3\xBA mandato (mi ha)", before: "16,3", after: "30,8", change: "+89%", positive: false, sources: [{ label: "MapBiomas Fogo", url: "https://brasil.mapbiomas.org/" }] }
        ]
      }
    ],
    chart1: {
      title: "Crescimento do PIB Nacional ao longo dos 3 mandatos (%)",
      unit: "%",
      positiveTrend: true,
      data: splitSeries([
        { ano: "2002", value: 3.1, current: false },
        { ano: "2003", value: 1.1, current: true },
        { ano: "2004", value: 5.8, current: true },
        { ano: "2006", value: 4, current: true },
        { ano: "2008", value: 5.1, current: true },
        { ano: "2010", value: 7.5, current: true },
        { ano: "2014", value: 0.5, current: false },
        { ano: "2019", value: 1.2, current: false },
        { ano: "2022", value: 3, current: false },
        { ano: "2023", value: 2.9, current: true },
        { ano: "2024", value: 3.2, current: true }
      ]),
      sources: [{ label: "IBGE \u2014 Contas Nacionais Trimestrais", url: "https://www.ibge.gov.br/explica/pib.php" }, { label: "IPEADATA", url: "http://www.ipeadata.gov.br/" }]
    },
    chart2: {
      title: "Desmatamento na Amaz\xF4nia ao longo dos 3 mandatos (km\xB2/ano)",
      unit: "km\xB2",
      positiveTrend: true,
      data: splitSeries([
        { ano: "2002", value: 21651, current: false },
        { ano: "2004", value: 27772, current: true },
        { ano: "2006", value: 14286, current: true },
        { ano: "2008", value: 12911, current: true },
        { ano: "2010", value: 7e3, current: true },
        { ano: "2014", value: 5012, current: false },
        { ano: "2019", value: 10129, current: false },
        { ano: "2022", value: 11594, current: false },
        { ano: "2023", value: 9001, current: true },
        { ano: "2024", value: 5816, current: true }
      ]),
      sources: [{ label: "INPE \u2014 PRODES", url: "http://terrabrasilis.dpi.inpe.br/app/dashboard/deforestation/biomes/legal_amazon/rates" }]
    },
    comparisonLabel: "Antecessores (FHC II e Bolsonaro)",
    footnote: "Dados consolidados ao longo dos tr\xEAs mandatos presidenciais de Lula (2003\u20132010 e 2023\u2013presente). Para o 1\xBA/2\xBA mandatos, a refer\xEAncia 'antes' \xE9 o final do governo FHC II (2002); para o 3\xBA, o final do governo Bolsonaro (2022). Indicadores apresentados de forma equilibrada \u2014 incluem avan\xE7os e retrocessos. Atualizado at\xE9 dezembro de 2024.",
    dataSources: [
      { label: "IBGE", url: "https://www.ibge.gov.br/" },
      { label: "IPEA / IPEADATA", url: "http://www.ipeadata.gov.br/" },
      { label: "INPE \u2014 PRODES e Queimadas", url: "http://terrabrasilis.dpi.inpe.br/" },
      { label: "FAO \u2014 SOFI", url: "https://www.fao.org/publications/sofi/" },
      { label: "MDS \u2014 Bolsa Fam\xEDlia", url: "https://www.gov.br/mds/pt-br/" },
      { label: "Banco Central do Brasil", url: "https://www.bcb.gov.br/" },
      { label: "Tesouro Nacional", url: "https://www.gov.br/tesouronacional/" },
      { label: "Receita Federal", url: "https://www.gov.br/receitafederal/" },
      { label: "Minist\xE9rio da Sa\xFAde / DATASUS", url: "https://datasus.saude.gov.br/" },
      { label: "Datafolha", url: "https://datafolha.folha.uol.com.br/" },
      { label: "FBSP \u2014 Anu\xE1rio de Seguran\xE7a P\xFAblica", url: "https://forumseguranca.org.br/" },
      { label: "MapBiomas", url: "https://brasil.mapbiomas.org/" },
      { label: "PNUD \u2014 IDH", url: "https://www.undp.org/pt/brazil" },
      { label: "DIEESE", url: "https://www.dieese.org.br/" }
    ]
  },
  // Flávio Bolsonaro - Senador
  "2": {
    subtitle: "Indicadores parlamentares do mandato como Senador da Rep\xFAblica pelo Rio de Janeiro.",
    commitments: [
      { id: 1, title: "Defesa de pautas conservadoras", icon: ShieldCheck, status: "Em Andamento", progress: 70, detail: "Atua\xE7\xE3o ativa na CCJ" },
      { id: 2, title: "Redu\xE7\xE3o de impostos", icon: Landmark, status: "Em Andamento", progress: 30, detail: "Votos contr\xE1rios a aumentos tribut\xE1rios" },
      { id: 3, title: "Combate \xE0 corrup\xE7\xE3o", icon: ShieldCheck, status: "Em Andamento", progress: 25, detail: "Apoio a projetos de transpar\xEAncia" },
      { id: 4, title: "Seguran\xE7a p\xFAblica", icon: ShieldCheck, status: "Em Andamento", progress: 45, detail: "Defesa do excludente de ilicitude" },
      { id: 5, title: "Fim do foro privilegiado", icon: ShieldCheck, status: "N\xE3o Cumprida", progress: 10, detail: "PEC 333/2017 e correlatas seguem sem vota\xE7\xE3o; senador n\xE3o apresentou proposta pr\xF3pria sobre o tema" },
      { id: 6, title: "Aprovar lei de prote\xE7\xE3o a agentes de seguran\xE7a", icon: ShieldCheck, status: "N\xE3o Cumprida", progress: 15, detail: "Projetos arquivados ao fim das legislaturas sem aprova\xE7\xE3o no plen\xE1rio" },
      { id: 7, title: "Esclarecer caso das 'rachadinhas' do gabinete na ALERJ", icon: ShieldCheck, status: "N\xE3o Cumprida", progress: 0, detail: "Investiga\xE7\xE3o do MP-RJ ainda em curso; STJ rejeitou suspens\xE3o em 2023" }
    ],
    performance: [
      {
        title: "Atividade Legislativa",
        icon: FileText,
        metrics: [
          { label: "Projetos apresentados", before: "32", after: "58", change: "+81,3%", positive: true, sources: [{ label: "Senado \u2014 Atividade do Senador", url: "https://www25.senado.leg.br/web/senadores/senador/-/perfil/4988" }] },
          { label: "Discursos em plen\xE1rio", before: "45", after: "72", change: "+60,0%", positive: true, sources: [{ label: "Senado \u2014 Discursos", url: "https://www25.senado.leg.br/web/atividade/pronunciamentos" }] },
          { label: "Relatorias assumidas", before: "8", after: "14", change: "+75,0%", positive: true, sources: [{ label: "Senado \u2014 Relatorias", url: "https://www25.senado.leg.br/web/atividade/materias" }] }
        ]
      },
      {
        title: "Participa\xE7\xE3o",
        icon: Vote,
        metrics: [
          { label: "Presen\xE7a em vota\xE7\xF5es", before: "82%", after: "89%", change: "+7,0 p.p.", positive: true, sources: [{ label: "Senado \u2014 Vota\xE7\xF5es Nominais", url: "https://www25.senado.leg.br/web/atividade/plenario/votacoes" }] },
          { label: "Audi\xEAncias p\xFAblicas em comiss\xF5es", before: "12", after: "21", change: "+75,0%", positive: true, sources: [{ label: "Senado \u2014 Comiss\xF5es", url: "https://www25.senado.leg.br/web/atividade/comissoes" }] }
        ]
      },
      {
        title: "Indicadores Cr\xEDticos",
        icon: ShieldCheck,
        metrics: [
          { label: "Projetos aprovados pelo plen\xE1rio (sancionados)", before: "4", after: "2", change: "-50,0%", positive: false, sources: [{ label: "Senado \u2014 Mat\xE9rias do Senador", url: "https://www25.senado.leg.br/web/senadores/senador/-/perfil/4988" }] },
          { label: "Faltas em vota\xE7\xF5es secretas", before: "6", after: "11", change: "+83,3%", positive: false, sources: [{ label: "Senado \u2014 Vota\xE7\xF5es", url: "https://www25.senado.leg.br/web/atividade/plenario/votacoes" }] },
          { label: "Processos em investiga\xE7\xE3o (MP-RJ \u2014 'rachadinhas')", before: "1", after: "1 (ativo)", change: "Sem desfecho", positive: false, sources: [{ label: "MP-RJ \u2014 Notas Oficiais", url: "https://www.mprj.mp.br/" }, { label: "STJ \u2014 APn 989", url: "https://www.stj.jus.br/" }] },
          { label: "Alinhamento com pauta do governo eleito (2023\u20132024)", before: "\u2014", after: "18%", change: "Oposi\xE7\xE3o sistem\xE1tica", positive: false, sources: [{ label: "DIAP \u2014 Radiografia do Congresso", url: "https://www.diap.org.br/" }] }
        ]
      }
    ],
    chart1: {
      title: "Projetos de Lei Apresentados",
      unit: "projetos",
      positiveTrend: true,
      data: splitSeries([
        { ano: "2019", value: 12, current: false },
        { ano: "2020", value: 14, current: false },
        { ano: "2021", value: 18, current: false },
        { ano: "2022", value: 16, current: false },
        { ano: "2023", value: 28, current: true },
        { ano: "2024", value: 30, current: true }
      ]),
      sources: [{ label: "Senado \u2014 Atividade Legislativa", url: "https://www25.senado.leg.br/web/atividade/materias" }]
    },
    chart2: {
      title: "Presen\xE7a em Vota\xE7\xF5es Nominais (%)",
      unit: "%",
      positiveTrend: true,
      data: splitSeries([
        { ano: "2019", value: 78, current: false },
        { ano: "2020", value: 80, current: false },
        { ano: "2021", value: 83, current: false },
        { ano: "2022", value: 82, current: false },
        { ano: "2023", value: 87, current: true },
        { ano: "2024", value: 89, current: true }
      ]),
      sources: [{ label: "Senado \u2014 Vota\xE7\xF5es Nominais", url: "https://www25.senado.leg.br/web/atividade/plenario/votacoes" }]
    },
    comparisonLabel: "1\xBA Mandato (2019\u20132022)",
    footnote: "Compara\xE7\xE3o entre o 1\xBA mandato (2019\u20132022) e o 2\xBA mandato em curso de Fl\xE1vio Bolsonaro como Senador. Dados consolidados at\xE9 dezembro de 2024.",
    dataSources: [
      { label: "Senado Federal", url: "https://www25.senado.leg.br/" },
      { label: "Portal da Transpar\xEAncia", url: "https://portaldatransparencia.gov.br/" }
    ]
  },
  "3": {
    subtitle: "Indicadores parlamentares do mandato na Assembleia Legislativa do Rio de Janeiro.",
    commitments: [
      { id: 1, title: "Investimento em educa\xE7\xE3o", icon: GraduationCap, status: "Em Andamento", progress: 68, detail: "Aumento real no or\xE7amento da educa\xE7\xE3o" },
      { id: 2, title: "Habita\xE7\xE3o popular", icon: Building2, status: "Em Andamento", progress: 55, detail: "2.700 de 5.000 unidades em obras" },
      { id: 3, title: "Valoriza\xE7\xE3o do professor", icon: GraduationCap, status: "Em Andamento", progress: 60, detail: "Reajuste salarial em discuss\xE3o" },
      { id: 4, title: "Infraestrutura estadual", icon: Building2, status: "Parcialmente Cumprida", progress: 72, detail: "Projetos aprovados em 2023-2024" },
      { id: 5, title: "Reduzir letalidade policial no RJ", icon: ShieldCheck, status: "N\xE3o Cumprida", progress: 10, detail: "RJ segue como estado com maior n\xFAmero absoluto de mortes por interven\xE7\xE3o policial (Anu\xE1rio FBSP 2024)" },
      { id: 6, title: "Zerar fila da sa\xFAde estadual", icon: Stethoscope, status: "N\xE3o Cumprida", progress: 15, detail: "Fila por cirurgias eletivas e consultas especializadas cresceu em 2023\u20132024" },
      { id: 7, title: "Concluir obras paradas do estado", icon: Building2, status: "Parcialmente Cumprida", progress: 35, detail: "TCE-RJ aponta dezenas de obras com atraso superior a 24 meses" }
    ],
    performance: [
      {
        title: "Atividade Legislativa",
        icon: FileText,
        metrics: [
          { label: "Projetos apresentados", before: "18", after: "34", change: "+88,9%", positive: true },
          { label: "Emendas ao or\xE7amento", before: "12", after: "21", change: "+75,0%", positive: true }
        ]
      },
      {
        title: "Participa\xE7\xE3o",
        icon: Vote,
        metrics: [
          { label: "Presen\xE7a em sess\xF5es", before: "85%", after: "94%", change: "+9,0 p.p.", positive: true },
          { label: "Audi\xEAncias p\xFAblicas realizadas", before: "6", after: "13", change: "+116,7%", positive: true }
        ]
      },
      {
        title: "Indicadores Cr\xEDticos do Estado",
        icon: ShieldCheck,
        metrics: [
          { label: "Mortes por interven\xE7\xE3o policial (RJ)", before: "1.245", after: "1.330", change: "+6,8%", positive: false, sources: [{ label: "ISP-RJ \u2014 Estat\xEDsticas", url: "http://www.ispdados.rj.gov.br/" }, { label: "FBSP \u2014 Anu\xE1rio 2024", url: "https://forumseguranca.org.br/anuario-brasileiro-seguranca-publica/" }] },
          { label: "Fila por cirurgia eletiva no SUS-RJ", before: "62 mil", after: "84 mil", change: "+35,5%", positive: false, sources: [{ label: "SES-RJ \u2014 Painel SUS", url: "https://www.saude.rj.gov.br/" }] },
          { label: "Evas\xE3o no Ensino M\xE9dio (RJ)", before: "6,8%", after: "7,9%", change: "+1,1 p.p.", positive: false, sources: [{ label: "INEP \u2014 Censo Escolar", url: "https://www.gov.br/inep/pt-br/areas-de-atuacao/pesquisas-estatisticas-e-indicadores/censo-escolar" }] },
          { label: "Obras estaduais com atraso > 24 meses", before: "\u2014", after: "47", change: "Cr\xEDtico", positive: false, sources: [{ label: "TCE-RJ \u2014 Relat\xF3rios", url: "https://www.tce.rj.gov.br/" }] }
        ]
      }
    ],
    chart1: {
      title: "Projetos de Lei Apresentados",
      unit: "projetos",
      positiveTrend: true,
      data: splitSeries([
        { ano: "2019", value: 6, current: false },
        { ano: "2020", value: 8, current: false },
        { ano: "2021", value: 10, current: false },
        { ano: "2022", value: 12, current: false },
        { ano: "2023", value: 16, current: true },
        { ano: "2024", value: 18, current: true }
      ])
    },
    chart2: {
      title: "Presen\xE7a em Sess\xF5es (%)",
      unit: "%",
      positiveTrend: true,
      data: splitSeries([
        { ano: "2019", value: 82, current: false },
        { ano: "2020", value: 84, current: false },
        { ano: "2021", value: 86, current: false },
        { ano: "2022", value: 85, current: false },
        { ano: "2023", value: 92, current: true },
        { ano: "2024", value: 94, current: true }
      ])
    },
    comparisonLabel: "Mandato Anterior",
    footnote: "Fontes: ALERJ, Portal da Transpar\xEAncia do RJ. Dados consolidados at\xE9 dezembro de 2024."
  },
  // Ronaldo Caiado - Governador de Goiás
  "4": {
    subtitle: "Resultados concretos e compromissos assumidos durante o mandato de Ronaldo Caiado como Governador de Goi\xE1s.",
    commitments: [
      { id: 1, title: "Pacto pela Seguran\xE7a", icon: ShieldCheck, status: "Cumprida", progress: 100, detail: "Goi\xE1s entre os estados mais seguros" },
      { id: 2, title: "Goi\xE1s na Frente (10 mil km de estradas)", icon: BriefcaseBusiness, status: "Em Andamento", progress: 60, detail: "6 mil km j\xE1 asfaltados" },
      { id: 3, title: "Equil\xEDbrio fiscal do estado", icon: Landmark, status: "Cumprida", progress: 100, detail: "Contas equilibradas, sem aumento de impostos" },
      { id: 4, title: "Programa Goi\xE1s Social", icon: Stethoscope, status: "Em Andamento", progress: 78, detail: "Cobertura ampliada em 70% dos munic\xEDpios" },
      { id: 5, title: "Constru\xE7\xE3o de escolas em tempo integral", icon: GraduationCap, status: "Parcialmente Cumprida", progress: 65, detail: "210 de 320 unidades entregues" },
      { id: 6, title: "Saneamento b\xE1sico universal", icon: Droplets, status: "Em Andamento", progress: 55, detail: "Cobertura passou de 38% para 58%" },
      { id: 7, title: "Zerar desmatamento ilegal no Cerrado goiano", icon: ShieldCheck, status: "N\xE3o Cumprida", progress: 10, detail: "GO segue entre os estados com maior alerta de desmatamento do Cerrado (MapBiomas/INPE 2024)" },
      { id: 8, title: "Universalizar atendimento b\xE1sico de sa\xFAde", icon: Stethoscope, status: "Parcialmente Cumprida", progress: 50, detail: "Fila por consultas e cirurgias eletivas cresceu em 2023" },
      { id: 9, title: "Renegociar d\xEDvida do estado com a Uni\xE3o", icon: Landmark, status: "N\xE3o Cumprida", progress: 20, detail: "GO ainda n\xE3o aderiu ao RRF; estoque da d\xEDvida segue elevado" }
    ],
    performance: [
      {
        title: "Seguran\xE7a P\xFAblica",
        icon: ShieldCheck,
        metrics: [
          { label: "Taxa de homic\xEDdios (por 100 mil hab.)", before: "33,8", after: "11,1", change: "-67,2%", positive: true, sources: [{ label: "FBSP \u2014 Anu\xE1rio Brasileiro de Seguran\xE7a P\xFAblica", url: "https://forumseguranca.org.br/anuario-brasileiro-seguranca-publica/" }] },
          { label: "Roubos de ve\xEDculos", before: "12.450", after: "5.890", change: "-52,7%", positive: true, sources: [{ label: "SSP-GO \u2014 Estat\xEDsticas", url: "https://www.ssp.go.gov.br/estatistica" }] },
          { label: "Mortes violentas intencionais", before: "2.231", after: "740", change: "-66,8%", positive: true, sources: [{ label: "SSP-GO \u2014 Estat\xEDsticas", url: "https://www.ssp.go.gov.br/estatistica" }] }
        ]
      },
      {
        title: "Economia",
        icon: TrendingUp,
        metrics: [
          { label: "Crescimento do PIB estadual", before: "1,4%", after: "4,1%", change: "+2,7 p.p.", positive: true, sources: [{ label: "IBGE \u2014 Contas Regionais", url: "https://www.ibge.gov.br/estatisticas/economicas/contas-nacionais/9054-contas-regionais-do-brasil.html" }] },
          { label: "Empregos formais (saldo CAGED)", before: "62 mil", after: "138 mil", change: "+122,6%", positive: true, sources: [{ label: "MTE \u2014 Novo CAGED", url: "https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/estatisticas-trabalho/novo-caged" }] },
          { label: "Capacidade de pagamento (CAPAG)", before: "C", after: "B", change: "Melhora", positive: true, sources: [{ label: "Tesouro Nacional \u2014 CAPAG", url: "https://www.tesourotransparente.gov.br/temas/estados-e-municipios/capacidade-de-pagamento-capag" }] }
        ]
      },
      {
        title: "Social e Educa\xE7\xE3o",
        icon: Users,
        metrics: [
          { label: "Pobreza extrema", before: "8,2%", after: "4,9%", change: "-3,3 p.p.", positive: true, sources: [{ label: "IBGE \u2014 PNAD Cont\xEDnua", url: "https://www.ibge.gov.br/estatisticas/sociais/populacao/9221-sintese-de-indicadores-sociais.html" }] },
          { label: "Cobertura do Goi\xE1s Social", before: "0%", after: "70%", change: "+70 p.p.", positive: true, sources: [{ label: "OVG \u2014 Goi\xE1s Social", url: "https://www.social.go.gov.br/goias-social" }] },
          { label: "Escolas em tempo integral", before: "85", after: "295", change: "+247%", positive: true, sources: [{ label: "Seduc-GO", url: "https://site.educacao.go.gov.br/" }] }
        ]
      },
      {
        title: "Indicadores Cr\xEDticos",
        icon: ShieldCheck,
        metrics: [
          { label: "Alertas de desmatamento no Cerrado (GO, km\xB2)", before: "612", after: "1.034", change: "+68,9%", positive: false, sources: [{ label: "INPE \u2014 DETER Cerrado", url: "http://terrabrasilis.dpi.inpe.br/" }, { label: "MapBiomas Alerta", url: "https://alerta.mapbiomas.org/" }] },
          { label: "Estoque da d\xEDvida consolidada (R$ bi)", before: "16,4", after: "22,1", change: "+34,8%", positive: false, sources: [{ label: "Tesouro Nacional \u2014 Estados", url: "https://www.tesourotransparente.gov.br/temas/estados-e-municipios" }] },
          { label: "Fila por cirurgia eletiva no SUS-GO", before: "28 mil", after: "41 mil", change: "+46,4%", positive: false, sources: [{ label: "SES-GO \u2014 Painel Sa\xFAde", url: "https://www.saude.go.gov.br/" }] },
          { label: "Mortes por interven\xE7\xE3o policial", before: "112", after: "168", change: "+50,0%", positive: false, sources: [{ label: "FBSP \u2014 Anu\xE1rio 2024", url: "https://forumseguranca.org.br/anuario-brasileiro-seguranca-publica/" }] },
          { label: "Feminic\xEDdios consumados", before: "38", after: "57", change: "+50,0%", positive: false, sources: [{ label: "SSP-GO", url: "https://www.ssp.go.gov.br/estatistica" }] }
        ]
      }
    ],
    chart1: {
      title: "Evolu\xE7\xE3o do PIB Estadual (%)",
      unit: "%",
      positiveTrend: true,
      data: splitSeries([
        { ano: "2017", value: 0.9, current: false },
        { ano: "2018", value: 1.4, current: false },
        { ano: "2019", value: 2.1, current: true },
        { ano: "2020", value: -2, current: true },
        { ano: "2021", value: 3.5, current: true },
        { ano: "2022", value: 3.8, current: true },
        { ano: "2023", value: 4.1, current: true }
      ]),
      sources: [{ label: "IBGE \u2014 Contas Regionais", url: "https://www.ibge.gov.br/estatisticas/economicas/contas-nacionais/9054-contas-regionais-do-brasil.html" }]
    },
    chart2: {
      title: "Taxa de Homic\xEDdios (por 100 mil hab.)",
      unit: "por 100 mil",
      positiveTrend: true,
      data: splitSeries([
        { ano: "2017", value: 35.4, current: false },
        { ano: "2018", value: 33.8, current: false },
        { ano: "2019", value: 28.5, current: true },
        { ano: "2020", value: 24.1, current: true },
        { ano: "2021", value: 21.6, current: true },
        { ano: "2022", value: 19.4, current: true },
        { ano: "2023", value: 11.1, current: true }
      ]),
      sources: [{ label: "FBSP \u2014 Anu\xE1rio Brasileiro de Seguran\xE7a P\xFAblica", url: "https://forumseguranca.org.br/anuario-brasileiro-seguranca-publica/" }]
    },
    comparisonLabel: "Gov. Marconi Perillo (2011\u20132014)",
    footnote: "Compara\xE7\xE3o entre o \xFAltimo mandato completo do governo anterior (Marconi Perillo, PSDB) e o governo Caiado. Dados consolidados at\xE9 dezembro de 2024.",
    dataSources: [
      { label: "IBGE", url: "https://www.ibge.gov.br/" },
      { label: "SSP-GO", url: "https://www.ssp.go.gov.br/" },
      { label: "FBSP", url: "https://forumseguranca.org.br/" },
      { label: "Tesouro Nacional", url: "https://www.tesourotransparente.gov.br/" },
      { label: "Seduc-GO", url: "https://site.educacao.go.gov.br/" }
    ]
  },
  // Renan Santos - Deputado Federal NOVO/SP
  "5": {
    subtitle: "Indicadores parlamentares do mandato como Deputado Federal por S\xE3o Paulo.",
    commitments: [
      { id: 1, title: "Redu\xE7\xE3o da m\xE1quina p\xFAblica", icon: Landmark, status: "Em Andamento", progress: 40, detail: "Apoio \xE0 Reforma Administrativa" },
      { id: 2, title: "Combate a privil\xE9gios", icon: ShieldCheck, status: "Em Andamento", progress: 55, detail: "Projetos contra penduricalhos" },
      { id: 3, title: "Desburocratiza\xE7\xE3o digital", icon: TrendingUp, status: "Em Andamento", progress: 35, detail: "Marco Legal das Startups apoiado" },
      { id: 4, title: "Fim do foro privilegiado", icon: ShieldCheck, status: "Em Andamento", progress: 30, detail: "Proposta em tramita\xE7\xE3o" },
      { id: 5, title: "Aprovar Reforma Administrativa (PEC 32)", icon: Landmark, status: "N\xE3o Cumprida", progress: 5, detail: "PEC sequer foi pautada no plen\xE1rio da C\xE2mara em 2023\u20132024" },
      { id: 6, title: "Acabar com o fund\xE3o eleitoral", icon: ShieldCheck, status: "N\xE3o Cumprida", progress: 0, detail: "Fundo eleitoral atingiu R$ 4,9 bi em 2024, recorde hist\xF3rico" },
      { id: 7, title: "Reduzir o n\xFAmero de minist\xE9rios", icon: Landmark, status: "N\xE3o Cumprida", progress: 0, detail: "N\xFAmero de minist\xE9rios passou de 23 para 38 na atual gest\xE3o" },
      { id: 8, title: "Aprovar projetos de autoria pr\xF3pria", icon: FileText, status: "N\xE3o Cumprida", progress: 8, detail: "Nenhum PL de autoria do deputado foi sancionado at\xE9 2024" }
    ],
    performance: [
      {
        title: "Atividade Legislativa",
        icon: FileText,
        metrics: [
          { label: "Projetos apresentados", before: "0", after: "26", change: "+26", positive: true, sources: [{ label: "C\xE2mara \u2014 Atividade do Deputado", url: "https://www.camara.leg.br/deputados/220552?ano=2024" }] },
          { label: "Discursos em plen\xE1rio", before: "0", after: "48", change: "+48", positive: true, sources: [{ label: "C\xE2mara \u2014 Discursos", url: "https://www.camara.leg.br/deputados/220552/discursos" }] },
          { label: "Requerimentos de informa\xE7\xE3o", before: "0", after: "62", change: "+62", positive: true, sources: [{ label: "C\xE2mara \u2014 Proposi\xE7\xF5es", url: "https://www.camara.leg.br/deputados/220552?ano=2024" }] }
        ]
      },
      {
        title: "Participa\xE7\xE3o",
        icon: Vote,
        metrics: [
          { label: "Presen\xE7a em vota\xE7\xF5es nominais", before: "\u2014", after: "92%", change: "92%", positive: true, sources: [{ label: "C\xE2mara \u2014 Vota\xE7\xF5es", url: "https://www.camara.leg.br/presenca-comissoes/presenca-plenario" }] },
          { label: "Audi\xEAncias p\xFAblicas", before: "0", after: "11", change: "+11", positive: true, sources: [{ label: "C\xE2mara \u2014 Comiss\xF5es", url: "https://www.camara.leg.br/comissoes" }] },
          { label: "Comiss\xF5es integradas", before: "0", after: "3", change: "+3", positive: true, sources: [{ label: "C\xE2mara \u2014 Atividade do Deputado", url: "https://www.camara.leg.br/deputados/220552" }] }
        ]
      },
      {
        title: "Indicadores Cr\xEDticos",
        icon: ShieldCheck,
        metrics: [
          { label: "Projetos de autoria aprovados pelo plen\xE1rio", before: "0", after: "0", change: "Sem aprova\xE7\xE3o", positive: false, sources: [{ label: "C\xE2mara \u2014 Proposi\xE7\xF5es", url: "https://www.camara.leg.br/deputados/220552?ano=2024" }] },
          { label: "Alinhamento com pautas do governo (2023\u20132024)", before: "\u2014", after: "12%", change: "Oposi\xE7\xE3o quase total", positive: false, sources: [{ label: "DIAP \u2014 Radiografia do Congresso", url: "https://www.diap.org.br/" }] },
          { label: "Faltas em sess\xF5es deliberativas", before: "\u2014", after: "34", change: "+34", positive: false, sources: [{ label: "C\xE2mara \u2014 Presen\xE7a", url: "https://www.camara.leg.br/presenca-comissoes/presenca-plenario" }] },
          { label: "Pautas do NOVO aprovadas em plen\xE1rio (Reforma Adm.)", before: "\u2014", after: "0", change: "Sem avan\xE7o", positive: false, sources: [{ label: "C\xE2mara \u2014 Tramita\xE7\xE3o PEC 32/2020", url: "https://www.camara.leg.br/proposicoesWeb/fichadetramitacao?idProposicao=2262083" }] }
        ]
      }
    ],
    chart1: {
      title: "Projetos de Lei Apresentados",
      unit: "projetos",
      positiveTrend: true,
      data: splitSeries([
        { ano: "2019", value: 0, current: false },
        { ano: "2020", value: 0, current: false },
        { ano: "2021", value: 0, current: false },
        { ano: "2022", value: 0, current: false },
        { ano: "2023", value: 14, current: true },
        { ano: "2024", value: 12, current: true }
      ]),
      sources: [{ label: "C\xE2mara \u2014 Proposi\xE7\xF5es do Deputado", url: "https://www.camara.leg.br/deputados/220552?ano=2024" }]
    },
    chart2: {
      title: "Presen\xE7a em Vota\xE7\xF5es Nominais (%)",
      unit: "%",
      positiveTrend: true,
      data: splitSeries([
        { ano: "2023", value: 90, current: true },
        { ano: "2024", value: 92, current: true }
      ]),
      sources: [{ label: "C\xE2mara \u2014 Presen\xE7a em Vota\xE7\xF5es", url: "https://www.camara.leg.br/presenca-comissoes/presenca-plenario" }]
    },
    comparisonLabel: "Antes do Mandato",
    footnote: "Compara\xE7\xE3o com o per\xEDodo anterior ao primeiro mandato (sem atividade parlamentar). Dados consolidados at\xE9 dezembro de 2024.",
    dataSources: [
      { label: "C\xE2mara dos Deputados", url: "https://www.camara.leg.br/" },
      { label: "Portal da Transpar\xEAncia", url: "https://portaldatransparencia.gov.br/" }
    ]
  },
  // Romeu Zema - Governador de MG
  "6": {
    subtitle: "Resultados concretos e compromissos assumidos durante o mandato de Romeu Zema como Governador de Minas Gerais.",
    commitments: [
      { id: 1, title: "Equil\xEDbrio fiscal de Minas", icon: Landmark, status: "Cumprida", progress: 100, detail: "D\xE9ficit recorrente eliminado" },
      { id: 2, title: "Pagar servidores em dia", icon: BriefcaseBusiness, status: "Cumprida", progress: 100, detail: "Folha regularizada desde 2019" },
      { id: 3, title: "Concess\xF5es e PPPs", icon: Building2, status: "Em Andamento", progress: 70, detail: "12 projetos contratados" },
      { id: 4, title: "Minas Livre para Crescer", icon: TrendingUp, status: "Cumprida", progress: 100, detail: "Lei sancionada em 2023" },
      { id: 5, title: "Reforma Administrativa", icon: Landmark, status: "Cumprida", progress: 100, detail: "Secretarias reduzidas e fundidas" },
      { id: 6, title: "Seguran\xE7a h\xEDdrica", icon: Droplets, status: "Em Andamento", progress: 50, detail: "Recupera\xE7\xE3o de bacias em curso" },
      { id: 7, title: "Resolver a d\xEDvida de MG com a Uni\xE3o", icon: Landmark, status: "N\xE3o Cumprida", progress: 25, detail: "MG segue fora do Regime de Recupera\xE7\xE3o Fiscal; estoque da d\xEDvida passou de R$ 120 bi" },
      { id: 8, title: "Reajuste e plano de carreira para servidores", icon: BriefcaseBusiness, status: "N\xE3o Cumprida", progress: 20, detail: "Categorias da educa\xE7\xE3o e seguran\xE7a realizaram greves em 2023\u20132024 por reajuste linear" },
      { id: 9, title: "Repara\xE7\xE3o integral das v\xEDtimas de Brumadinho", icon: ShieldCheck, status: "Parcialmente Cumprida", progress: 55, detail: "Acordo de R$ 37,7 bi assinado, mas MPMG aponta atrasos e atendimento incompleto a atingidos" },
      { id: 10, title: "Universalizar o ensino em tempo integral", icon: GraduationCap, status: "N\xE3o Cumprida", progress: 18, detail: "MG est\xE1 abaixo da meta do PNE para ensino m\xE9dio em tempo integral (INEP)" }
    ],
    performance: [
      {
        title: "Economia",
        icon: TrendingUp,
        metrics: [
          { label: "Crescimento do PIB estadual", before: "0,8%", after: "3,1%", change: "+2,3 p.p.", positive: true, sources: [{ label: "IBGE \u2014 Contas Regionais", url: "https://www.ibge.gov.br/estatisticas/economicas/contas-nacionais/9054-contas-regionais-do-brasil.html" }] },
          { label: "Resultado fiscal prim\xE1rio (R$ bi)", before: "-9,8", after: "+5,2", change: "Super\xE1vit", positive: true, sources: [{ label: "Tesouro Nacional \u2014 Estados", url: "https://www.tesourotransparente.gov.br/temas/estados-e-municipios" }] },
          { label: "Capacidade de pagamento (CAPAG)", before: "D", after: "C", change: "Melhora", positive: true, sources: [{ label: "Tesouro Nacional \u2014 CAPAG", url: "https://www.tesourotransparente.gov.br/temas/estados-e-municipios/capacidade-de-pagamento-capag" }] }
        ]
      },
      {
        title: "Administra\xE7\xE3o",
        icon: Landmark,
        metrics: [
          { label: "N\xFAmero de secretarias", before: "21", after: "14", change: "-33,3%", positive: true, sources: [{ label: "ALMG \u2014 Lei 24.313/2023", url: "https://www.almg.gov.br/legislacao-mineira/lei/24313/2023/" }] },
          { label: "Atrasos no pagamento de servidores", before: "Sim", after: "N\xE3o", change: "Regularizado", positive: true, sources: [{ label: "Portal da Transpar\xEAncia MG", url: "https://www.transparencia.mg.gov.br/" }] },
          { label: "Cargos comissionados", before: "8.230", after: "5.940", change: "-27,8%", positive: true, sources: [{ label: "Portal da Transpar\xEAncia MG", url: "https://www.transparencia.mg.gov.br/" }] }
        ]
      },
      {
        title: "Investimentos",
        icon: Building2,
        metrics: [
          { label: "Concess\xF5es e PPPs assinadas", before: "2", after: "12", change: "+500%", positive: true, sources: [{ label: "SEINFRA-MG", url: "https://www.infraestrutura.mg.gov.br/" }] },
          { label: "Investimento privado captado (R$ bi)", before: "4,1", after: "18,7", change: "+356,1%", positive: true, sources: [{ label: "Invest Minas", url: "https://www.investminas.mg.gov.br/" }] }
        ]
      },
      {
        title: "Indicadores Cr\xEDticos",
        icon: ShieldCheck,
        metrics: [
          { label: "D\xEDvida consolidada do estado (R$ bi)", before: "104,3", after: "162,8", change: "+56,1%", positive: false, sources: [{ label: "Tesouro Nacional \u2014 Estados", url: "https://www.tesourotransparente.gov.br/temas/estados-e-municipios" }] },
          { label: "Aprova\xE7\xE3o do governo (Quaest MG, 2024)", before: "58% \xF3timo/bom (2019)", after: "39% \xF3timo/bom", change: "-19 p.p.", positive: false, sources: [{ label: "Quaest \u2014 Pesquisa MG 2024", url: "https://quaest.com.br/" }] },
          { label: "Greves de servidores estaduais", before: "0", after: "5", change: "+5", positive: false, sources: [{ label: "Sind-UTE/MG", url: "https://sindutemg.org.br/" }] },
          { label: "V\xEDtimas de Brumadinho reparadas integralmente", before: "\u2014", after: "Parcial", change: "Acordo em atraso", positive: false, sources: [{ label: "MPMG \u2014 Acordo Brumadinho", url: "https://www.mpmg.mp.br/" }] },
          { label: "Matr\xEDculas no Ensino M\xE9dio em tempo integral (MG)", before: "Meta PNE: 50%", after: "23,4%", change: "-26,6 p.p. da meta", positive: false, sources: [{ label: "INEP \u2014 Censo Escolar", url: "https://www.gov.br/inep/pt-br/areas-de-atuacao/pesquisas-estatisticas-e-indicadores/censo-escolar" }] },
          { label: "Alertas de desmatamento no Cerrado (MG, km\xB2)", before: "238", after: "412", change: "+73,1%", positive: false, sources: [{ label: "INPE \u2014 DETER Cerrado", url: "http://terrabrasilis.dpi.inpe.br/" }] }
        ]
      }
    ],
    chart1: {
      title: "Resultado Fiscal Prim\xE1rio (R$ bilh\xF5es)",
      unit: "R$ bi",
      positiveTrend: true,
      data: splitSeries([
        { ano: "2017", value: -7.4, current: false },
        { ano: "2018", value: -9.8, current: false },
        { ano: "2019", value: -3.2, current: true },
        { ano: "2020", value: 1.5, current: true },
        { ano: "2021", value: 3.8, current: true },
        { ano: "2022", value: 4.6, current: true },
        { ano: "2023", value: 5.2, current: true }
      ]),
      sources: [{ label: "Tesouro Nacional \u2014 Estados e Munic\xEDpios", url: "https://www.tesourotransparente.gov.br/temas/estados-e-municipios" }]
    },
    chart2: {
      title: "Crescimento do PIB Estadual (%)",
      unit: "%",
      positiveTrend: true,
      data: splitSeries([
        { ano: "2017", value: 0.5, current: false },
        { ano: "2018", value: 0.8, current: false },
        { ano: "2019", value: 1.2, current: true },
        { ano: "2020", value: -3.8, current: true },
        { ano: "2021", value: 4.1, current: true },
        { ano: "2022", value: 2.8, current: true },
        { ano: "2023", value: 3.1, current: true }
      ]),
      sources: [{ label: "IBGE \u2014 Contas Regionais", url: "https://www.ibge.gov.br/estatisticas/economicas/contas-nacionais/9054-contas-regionais-do-brasil.html" }]
    },
    comparisonLabel: "Gov. Fernando Pimentel (2015\u20132018)",
    footnote: "Compara\xE7\xE3o entre o governo Pimentel (PT, 2015\u20132018) e o governo Zema (NOVO, 2019\u2013). Dados consolidados at\xE9 dezembro de 2024.",
    dataSources: [
      { label: "IBGE", url: "https://www.ibge.gov.br/" },
      { label: "Tesouro Nacional", url: "https://www.tesourotransparente.gov.br/" },
      { label: "Portal da Transpar\xEAncia MG", url: "https://www.transparencia.mg.gov.br/" },
      { label: "ALMG", url: "https://www.almg.gov.br/" }
    ]
  }
};

// src/lib/mcp/politicians.ts
function listPoliticians() {
  return mockPoliticians.map((p) => ({
    id: p.id,
    name: p.name,
    party: p.party,
    position: p.position,
    state: p.state,
    termStart: p.termStart,
    termEnd: p.termEnd,
    instagram: p.phone,
    website: p.website,
    counts: {
      votes: p.voteRecords.length,
      promises: p.promises.length,
      proposals: p.proposals.length
    }
  }));
}
function findPolitician(query) {
  const q = query.trim().toLowerCase();
  return mockPoliticians.find((p) => p.id === q) ?? mockPoliticians.find((p) => p.name.toLowerCase() === q) ?? mockPoliticians.find((p) => p.name.toLowerCase().includes(q)) ?? mockPoliticians.find((p) => p.party.toLowerCase() === q);
}
function politicianDetail(query) {
  const p = findPolitician(query);
  if (!p) return void 0;
  const { imageUrl: _imageUrl, phone, ...rest } = p;
  return { ...rest, instagram: phone };
}
function politicianLegacy(query) {
  const p = findPolitician(query);
  if (!p) return void 0;
  const legacy = legacyDataMap[p.id];
  if (!legacy) return void 0;
  return {
    politician: { id: p.id, name: p.name, position: p.position, party: p.party },
    subtitle: legacy.subtitle,
    comparisonLabel: legacy.comparisonLabel,
    footnote: legacy.footnote,
    commitments: legacy.commitments.map(({ icon: _icon, ...c }) => c),
    performance: legacy.performance.map(({ icon: _icon, ...cat }) => cat),
    dataSources: legacy.dataSources ?? []
  };
}
function platformStats() {
  return {
    politicians: mockPoliticians.length,
    votes: mockPoliticians.reduce((n, p) => n + p.voteRecords.length, 0),
    promises: mockPoliticians.reduce((n, p) => n + p.promises.length, 0),
    proposals: mockPoliticians.reduce((n, p) => n + p.proposals.length, 0)
  };
}

// src/lib/mcp/tools/list-politicians.ts
var list_politicians_default = defineTool({
  name: "list_politicians",
  title: "Listar pol\xEDticos",
  description: "Lista todos os pol\xEDticos monitorados na plataforma Polis, com partido, cargo, estado, mandato e contagem de votos, promessas e propostas.",
  inputSchema: {
    party: z.string().optional().describe("Filtrar por sigla do partido (ex.: PT, PL).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ party }) => {
    const all = listPoliticians();
    const items = party ? all.filter((p) => p.party.toLowerCase() === party.trim().toLowerCase()) : all;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { politicians: items }
    };
  }
});

// src/lib/mcp/tools/get-politician.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_politician_default = defineTool2({
  name: "get_politician",
  title: "Perfil do pol\xEDtico",
  description: "Retorna o perfil completo de um pol\xEDtico da Polis: biografia, mandatos, vota\xE7\xF5es, promessas e propostas, sempre com as fontes oficiais.",
  inputSchema: {
    politician: z2.string().describe("ID ou nome (parcial) do pol\xEDtico, ex.: 'Lula' ou '1'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ politician }) => {
    const data = politicianDetail(politician);
    if (!data) {
      return {
        content: [{ type: "text", text: `Nenhum pol\xEDtico encontrado para "${politician}".` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { politician: data }
    };
  }
});

// src/lib/mcp/tools/get-politician-legacy.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_politician_legacy_default = defineTool3({
  name: "get_politician_legacy",
  title: "Legado do pol\xEDtico",
  description: "Retorna o legado de um pol\xEDtico: compromissos (cumpridos, parciais e n\xE3o cumpridos) e indicadores de desempenho positivos e negativos, com fontes oficiais.",
  inputSchema: {
    politician: z3.string().describe("ID ou nome (parcial) do pol\xEDtico.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ politician }) => {
    const data = politicianLegacy(politician);
    if (!data) {
      return {
        content: [{ type: "text", text: `Legado n\xE3o encontrado para "${politician}".` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { legacy: data }
    };
  }
});

// src/lib/mcp/tools/get-platform-stats.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
var get_platform_stats_default = defineTool4({
  name: "get_platform_stats",
  title: "Estat\xEDsticas da plataforma",
  description: "Retorna os n\xFAmeros atuais da Polis: pol\xEDticos monitorados, vota\xE7\xF5es registradas, promessas e propostas acompanhadas.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const stats = platformStats();
    return {
      content: [{ type: "text", text: JSON.stringify(stats, null, 2) }],
      structuredContent: stats
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "polis",
  title: "Polis",
  version: "0.1.0",
  instructions: "Ferramentas p\xFAblicas da Polis, plataforma brasileira de transpar\xEAncia pol\xEDtica. Use `list_politicians` para descobrir os pol\xEDticos monitorados, `get_politician` para o perfil completo (vota\xE7\xF5es, promessas e propostas com fontes), `get_politician_legacy` para o balan\xE7o de legado com indicadores positivos e negativos, e `get_platform_stats` para os n\xFAmeros agregados da plataforma. Todos os dados citam fontes oficiais brasileiras.",
  tools: [list_politicians_default, get_politician_default, get_politician_legacy_default, get_platform_stats_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
